-- [ GENERATED CHANGELOG DATA ] ----------------------------------------------------
-- This file is automatically generated by update_changelog.py. Do not edit.

local _, addonTable = ...
local Orbit = addonTable

Orbit.LatestChangelogVersion = "@project-version@"

Orbit.WHATS_NEW_ENTRIES = {
    { title = "Message", body = "- This is an automated test of the new changelog system!\\n- Thanks for sticking with Orbit." },
    { title = "Added", body = "- Automated `CHANGELOG.md` integration with in-game \\\"What's New\\\" prompt.\\n- Scripted update process for release workflows." },
    { title = "Fixed", body = "- Syncing version information across multiple files." },
}
