-- [ GENERATED CHANGELOG DATA ] ----------------------------------------------------------------------
-- This file is automatically generated by update_changelog.py. Do not edit.

local _, Orbit = ...

Orbit.LatestChangelogVersion = "@project-version@"

Orbit.WHATS_NEW_ENTRIES = {
    { title = "Message", body = "DO NOT EDIT" },
    { title = "Added", body = "DO NOT EDIT" },
    { title = "Changed", body = "DO NOT EDIT" },
    { title = "Fixed", body = "DO NOT EDIT" },
}
