local _, Orbit = ...

-- [ DEFAULT PROFILE ]-------------------------------------------------------------------------------
Orbit.Profile = Orbit.Profile or {}
Orbit.Profile.defaults = {
    Layouts = {
        ["Orbit"] = {
            ["Orbit_FocusCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 0,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    CastBarWidth = 200,
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_QueueStatus"] = {
                ["Orbit_QueueStatus"] = {
                    Anchor = false,
                    Position = {
                        y = -4,
                        x = -343,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_FocusFrame"] = {
                [3] = {
                    EnableFocusTarget = false,
                    EnableFocusPower = true,
                    ReactionColour = false,
                    PortraitStyle = "3d",
                    DisabledComponents = {
                        "Portrait",
                    },
                    Width = 99,
                    Is3D = true,
                    PortraitBorder = true,
                    PortraitShape = "square",
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 42,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    PortraitScale = 125,
                    EnableBuffs = false,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -2,
                            posY = 14.04274130149705,
                            posX = 81.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 5.923077103654316,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 19.96581840515137,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            posY = 0,
                            posX = 74.86327362060547,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -7.923077103654316,
                            posY = -12.11966419784274,
                            posX = 87.78635072425979,
                            justifyH = "LEFT",
                            offsetY = 7.846154207308631,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Portrait = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 4,
                            anchorY = "CENTER",
                        },
                    },
                    Height = 26,
                },
            },
            ["Orbit_CooldownViewer"] = {
                [1] = {
                    IconLimit = 12,
                    ShowGCDSwipe = true,
                    Opacity = 100,
                    PandemicGlowType = 2,
                    DisabledComponents = {
                        "Status",
                        "Keybind",
                    },
                    ActiveSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.7696304321289062, r = 1, g = 0.9490196704864502, b = 0.5686274766921997 },
                                position = 0.4343791964382053,
                            },
                        },
                    },
                    aspectRatio = "4:3",
                    IconSize = 100,
                    Position = {
                        y = 274.5983006704963,
                        x = 0.2734813094139099,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    CooldownSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.800000011920929, r = 0, g = 0, b = 0 },
                                position = 0.4649682788830493,
                            },
                        },
                    },
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    IconPadding = 0,
                },
                [2] = {
                    IconLimit = 8,
                    Opacity = 100,
                    IconPadding = 2,
                    ActiveSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.7696304321289062, r = 1, g = 0.9490196704864502, b = 0.5686274766921997 },
                                position = 0.4343791964382053,
                            },
                        },
                    },
                    aspectRatio = "4:3",
                    PandemicGlowType = 2,
                    Position = {
                        y = 213.8800811767578,
                        x = -0.0002154724206775427,
                        point = "BOTTOM",
                    },
                    CooldownSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.800000011920929, r = 0, g = 0, b = 0 },
                                position = 0.4649682788830493,
                            },
                        },
                    },
                    Anchor = false,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -11,
                            offsetX = 1,
                            posX = -17,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    IconSize = 100,
                },
                [3] = {
                    IconLimit = 10,
                    CooldownSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.800000011920929, r = 0, g = 0, b = 0 },
                                position = 0.4649682788830493,
                            },
                        },
                    },
                    Opacity = 100,
                    IconPadding = 1,
                    IconSize = 100,
                    ActiveSwipeColorCurve = {
                        pins = {
                            {
                                color = { a = 0.7696304321289062, r = 1, g = 0.9490196704864502, b = 0.5686274766921997 },
                                position = 0.4343791964382053,
                            },
                        },
                    },
                    aspectRatio = "4:3",
                    PandemicGlowColor = { a = 1, r = 1, g = 0.2196078431372549, b = 0 },
                    Anchor = {
                        target = "OrbitPlayerPower",
                        padding = 15,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    PandemicGlowType = 1,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    DisabledComponents = {
                        "Status",
                        "Keybind",
                    },
                },
                [4] = {
                    aspectRatio = "1:1",
                    Position = {
                        y = -0.2734985765385964,
                        x = -31.99999546675529,
                        point = "CENTER",
                    },
                    Anchor = false,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            posY = -13.54871780826886,
                            offsetX = 0,
                            posX = 14.62222339597525,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                    DisabledComponents = {
                        "Status",
                        "Keybind",
                    },
                },
                [20] = {
                    ComponentPositions = {
                        ChargeCount = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "Status",
                    },
                },
                [30] = {
                    BarColor1 = {
                        pins = {
                            {
                                color = { a = 1, b = 0.3019607843137255, g = 0.7019607843137254, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    BarColor2 = {
                        pins = {
                            {
                                color = { a = 1, b = 0.3019607843137255, g = 0.7019607843137254, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    BarColor3 = {
                        pins = {
                            {
                                color = { a = 1, b = 0.3019607843137255, g = 0.7019607843137254, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    BarColor4 = {
                        pins = {
                            {
                                color = { a = 1, b = 0.3019607843137255, g = 0.7019607843137254, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    BarColor5 = {
                        pins = {
                            {
                                color = { a = 1, b = 0.3019607843137255, g = 0.7019607843137254, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    DisabledComponents = {
                        "Status",
                    },
                    Spacing = 0,
                    Height = 22,
                    ComponentPositions = {
                        BuffBarName = {
                            posY = 0,
                            offsetX = 25,
                            posX = -46.55555340994511,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        BuffBarTimer = {
                            posY = 0,
                            offsetX = 5,
                            posX = 85.70085430145264,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                    },
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 0,
                        edge = "TOP",
                        align = "CENTER",
                    },
                },
            },
            ["Orbit_BagBar"] = {
                ["Orbit_BagBar"] = {
                    Anchor = {
                        target = "OrbitMicroMenuContainer",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Opacity = 100,
                    Scale = 100,
                },
            },
            ["Orbit_Status"] = {
                [1] = {
                    Height = 16,
                    Position = "TOP",
                },
            },
            ["Orbit_TargetDebuffs"] = {
                [1] = {
                    MaxRows = 1,
                    PandemicGlowColorCurve = {
                        pins = {
                            {
                                color = { a = 1, b = 0, g = 0.2274509803921569, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    IconsPerRow = 5,
                    Scale = 100,
                    PandemicGlowType = 1,
                    Anchor = {
                        target = "OrbitTargetCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
            },
            ["Orbit_FocusDebuffs"] = {
                [1] = {
                    MaxRows = 1,
                    PandemicGlowColorCurve = {
                        pins = {
                            {
                                color = { a = 1, b = 0, g = 0.1647058823529412, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    Spacing = 2,
                    IconsPerRow = 5,
                    Anchor = {
                        target = "OrbitFocusCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    PandemicGlowType = 1,
                    Scale = 100,
                },
            },
            ["Orbit_TalkingHead"] = {
                ["Orbit_TalkingHead"] = {
                    Anchor = false,
                    Scale = 60,
                    Position = {
                        y = -123,
                        x = 0,
                        point = "TOP",
                    },
                },
            },
            ["Orbit_Tour"] = {
                ["A"] = { Width = 150, Height = 50 },
                ["B"] = { Width = 150, Height = 50 },
            },
            ["Orbit_RaidFrames"] = {
                [1] = {
                    GroupsPerRow = 6,
                    ShowHealthValue = false,
                    Position = {
                        y = -118.2,
                        x = 97.9,
                        point = "TOPLEFT",
                    },
                    Width = 100,
                    DispelFrequency = 0.2,
                    Height = 40,
                    MemberSpacing = 2,
                    GroupSpacing = 2,
                    Orientation = "Horizontal",
                    Anchor = false,
                    DisabledComponents = {
                        "DefensiveIcon",
                        "CrowdControlIcon",
                        "Status",
                        "HealerAura1",
                        "HealerAura2",
                        "HealerAura3",
                        "HealerAura4",
                        "HealerAura5",
                        "HealerAura6",
                        "HealerAura7",
                        "RaidBuff",
                    },
                    ComponentPositions = {
                        StatusIcons = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ResIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Debuffs = {
                            overrides = {
                                MaxIcons = 2,
                                MaxRows = 3,
                                IconSize = 10,
                            },
                            posY = -9,
                            offsetX = 1,
                            posX = -45.1,
                            justifyH = "LEFT",
                            offsetY = 1,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            overrides = {
                                Scale = 0.8,
                            },
                            posY = 20,
                            offsetX = 8,
                            posX = -42.1,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 0,
                            overrides = {
                                FontSize = 10,
                                ShowHealthValue = false,
                                HealthTextMode = "percent_short",
                            },
                            posY = -10.1,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 9.8,
                            anchorX = "CENTER",
                            anchorY = "BOTTOM",
                        },
                        CrowdControlIcon = {
                            anchorX = "CENTER",
                            offsetY = 2,
                            offsetX = 0,
                            anchorY = "TOP",
                        },
                        DefensiveIcon = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 2,
                            anchorY = "CENTER",
                        },
                        Status = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        PrivateAuraAnchor = {
                            overrides = {
                                Scale = 1,
                            },
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        RoleIcon = {
                            overrides = {
                                Scale = 0.7,
                            },
                            posY = 18,
                            offsetX = 2,
                            posX = 48.1,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        MarkerIcon = {
                            posY = 21,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = -1,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        Name = {
                            posY = 10,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 10,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        PhaseIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        SummonIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            overrides = {
                                MaxIcons = 4,
                                MaxRows = 1,
                                IconSize = 15,
                            },
                            posY = -15,
                            offsetX = 1,
                            posX = 27.1,
                            justifyH = "RIGHT",
                            offsetY = 1,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        ReadyCheckIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        MainTankIcon = {
                            overrides = {
                                Scale = 0.6,
                            },
                            posY = 19.4,
                            offsetX = 17,
                            posX = -33,
                            justifyH = "LEFT",
                            offsetY = 0.5,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                    },
                },
            },
            ["Orbit_CombatTimer"] = {
                ["Orbit_CombatTimer"] = {
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 15,
                        edge = "LEFT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                    Scale = 100,
                    Position = {
                        y = 0,
                        relativeTo = "OrbitActionBar3",
                        point = "RIGHT",
                        relativePoint = "LEFT",
                        x = -9,
                    },
                },
            },
            ["Orbit_TargetPower"] = {
                [1] = {
                    Height = 7,
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ShowText = true,
                    Width = 205,
                },
            },
            ["Orbit_MicroMenu"] = {
                ["Orbit_MicroMenu"] = {
                    Anchor = false,
                    Padding = -5,
                    Rows = 1,
                    Position = {
                        y = 1,
                        x = 0,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_PartyFrames"] = {
                [1] = {
                    DisabledComponentsMigrated = true,
                    ShowPowerBar = false,
                    Spacing = 3,
                    Position = {
                        y = -466,
                        x = 446,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    IncludePlayer = true,
                    DisabledComponents = {
                        "DefensiveIcon",
                        "CrowdControlIcon",
                        "Status",
                        "HealerAura1",
                        "HealerAura2",
                        "HealerAura3",
                        "HealerAura4",
                        "HealerAura5",
                        "HealerAura6",
                        "HealerAura7",
                        "RaidBuff",
                    },
                    ComponentPositions = {
                        StatusIcons = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        RoleIcon = {
                            posY = 0,
                            offsetX = 5,
                            posX = -75,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Debuffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 18,
                            },
                            posX = 110,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            justifyH = "LEFT",
                            posY = 19.96581840515137,
                            posX = -69.86325073242188,
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            posY = 17.96581840515137,
                            posX = 0,
                            offsetY = 2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            posY = 0,
                            posX = 74.86325073242188,
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        CrowdControlIcon = {
                            anchorX = "CENTER",
                            offsetY = 2,
                            offsetX = 0,
                            anchorY = "TOP",
                        },
                        SummonIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        PrivateAuraAnchor = {
                            posY = 0,
                            offsetX = 0,
                            overrides = {
                                Scale = 1.2,
                            },
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 15,
                            justifyH = "LEFT",
                            posY = 0,
                            posX = -64.86325073242188,
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        ResIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        PhaseIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 18,
                            },
                            posX = -110,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        DefensiveIcon = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 2,
                            anchorY = "CENTER",
                        },
                    },
                },
            },
            ["Orbit_ActionBars"] = {
                [1] = {
                    NumActionBars = 6,
                    GlobalDisabledComponents = {
                        "Status",
                    },
                    Scale = 100,
                    Opacity = 100,
                    IconPadding = 0,
                    Position = {
                        y = 35.00854829265291,
                        x = -1.832860652939417e-05,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    NumIcons = 12,
                    GlobalComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            overrides = {
                                FontSize = 14,
                            },
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            offsetX = 0,
                            justifyH = "RIGHT",
                            posY = -10,
                            posX = 10,
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            offsetX = 0,
                            justifyH = "RIGHT",
                            posY = 10,
                            posX = 10,
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        MacroText = {
                            posY = -14,
                            offsetX = 1,
                            posX = -7,
                            justifyH = "LEFT",
                            overrides = {
                                FontSize = 10,
                            },
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    Rows = 1,
                },
                [2] = {
                    NumIcons = 12,
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 0,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Rows = 1,
                    IconPadding = 0,
                    Scale = 100,
                },
                [3] = {
                    NumIcons = 8,
                    Rows = 2,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 40,
                        edge = "LEFT",
                        align = "TOP",
                    },
                    Opacity = 100,
                    IconPadding = 0,
                    Scale = 100,
                },
                [4] = {
                    NumIcons = 8,
                    Rows = 2,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 40,
                        edge = "RIGHT",
                        align = "TOP",
                    },
                    Opacity = 100,
                    IconPadding = 0,
                    Scale = 100,
                },
                [5] = {
                    UseGlobalTextStyle = true,
                    Scale = 100,
                    Rows = 1,
                    IconPadding = 0,
                    Position = {
                        y = -3.282051402436211,
                        x = 4.923078060150147,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    NumIcons = 12,
                    HideEmptyButtons = false,
                    Opacity = 100,
                },
                [6] = {
                    Position = {
                        y = -48.41025161743164,
                        x = -2.188034296035767,
                        point = "RIGHT",
                    },
                    Scale = 90,
                    Rows = 12,
                    IconPadding = 0,
                    Anchor = false,
                },
                [7] = {
                    Position = {
                        y = -45.12821197509766,
                        x = -90.80342864990234,
                        point = "RIGHT",
                    },
                    Scale = 90,
                    Rows = 12,
                    IconPadding = 2,
                    Anchor = false,
                },
                [8] = {
                    Anchor = false,
                    Position = {
                        y = -45.67521667480469,
                        x = -45.40171432495117,
                        point = "RIGHT",
                    },
                    Scale = 90,
                    NumIcons = 12,
                    IconPadding = 2,
                    Rows = 12,
                },
                [9] = {
                    Opacity = 100,
                    OutOfCombatFade = false,
                    IconPadding = 2,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    Rows = 1,
                    HideEmptyButtons = true,
                    Scale = 80,
                },
                [10] = {
                    Rows = 1,
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Opacity = 100,
                    IconPadding = 2,
                    Scale = 80,
                },
                [11] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Rows = 1,
                    IconPadding = 2,
                    Scale = 80,
                },
                [12] = {
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 271,
                        x = -252,
                        point = "BOTTOM",
                    },
                },
                [13] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
            },
            ["Orbit_PlayerFrame"] = {
                [1] = {
                    ShowCombatIcon = true,
                    ShowHealAbsorbs = true,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            posY = 12.05129241943359,
                            posX = 82.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        GroupPositionText = {
                            offsetX = -3,
                            posY = -12.05129241943359,
                            posX = 82.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            posY = 18.05129241943359,
                            posX = -69.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        PvpIcon = {
                            posY = -23.05129241943359,
                            offsetX = 10,
                            posX = 69.86327362060547,
                            justifyH = "RIGHT",
                            overrides = {
                                Scale = 1.5,
                            },
                            offsetY = -5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        HealthText = {
                            offsetX = 4.9,
                            posY = 0,
                            posX = 74.96327362060546,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RestingIcon = {
                            posY = 13.05129241943359,
                            offsetX = 10,
                            posX = -69.86327362060547,
                            justifyH = "LEFT",
                            overrides = {
                                Scale = 0.5,
                            },
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Portrait = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 4,
                            anchorY = "CENTER",
                        },
                        CombatIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 18.05129241943359,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        RoleIcon = {
                            anchorX = "RIGHT",
                            offsetY = 3,
                            offsetX = 10,
                            anchorY = "TOP",
                        },
                    },
                    PortraitMirror = false,
                    Width = 160,
                    PortraitStyle = "3d",
                    DisabledComponents = {
                        "Status",
                        "Portrait",
                        "RoleIcon",
                    },
                    ShowAbsorbs = true,
                    Is3D = true,
                    PortraitBorder = true,
                    PortraitShape = "square",
                    Height = 36,
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 100,
                        edge = "LEFT",
                        align = "CENTER",
                    },
                    PortraitScale = 155,
                    TextSize = 12,
                    ShowLevel = true,
                },
            },
            ["Orbit_PlayerDebuffs"] = {
                [1] = {
                    Anchor = false,
                    IconLimit = 10,
                    Spacing = 0,
                    Position = {
                        y = -3.282051402436211,
                        x = -251.0769348144531,
                        point = "TOPRIGHT",
                    },
                },
            },
            ["Orbit_PlayerPower"] = {
                [1] = {
                    ShowText = false,
                    Anchor = {
                        target = "OrbitPlayerResources",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    DisabledComponents = {
                    },
                    ComponentPositions = {
                        Text = {
                            offsetX = 4.923077103654316,
                            posY = 0,
                            posX = 179.9658185669189,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                    },
                    Height = 10,
                },
            },
            ["Orbit_PlayerResources"] = {
                [1] = {
                    Width = 200,
                    ShowText = true,
                    Spacing = 2,
                    Height = 12,
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    TextSize = 15,
                    DividerSize = 2,
                },
            },
            [13] = {
                [13] = {
                    Size = 100,
                    EyeSize = 100,
                },
            },
            [14] = {
                [14] = {
                    Size = 70,
                },
            },
            ["Orbit_TargetFrame"] = {
                [2] = {
                    PortraitMirror = true,
                    AuraSize = 20,
                    Is3D = false,
                    PortraitStyle = "2d",
                    DisabledComponents = {
                        "Portrait",
                    },
                    MaxBuffs = 16,
                    EnableTargetPower = true,
                    PortraitBorder = true,
                    PortraitShape = "square",
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 100,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    Height = 36,
                    PortraitScale = 125,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = 0,
                            posY = 15,
                            posX = 79.9,
                            justifyH = "LEFT",
                            offsetY = 4.9,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        Portrait = {
                            offsetX = 4,
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        HealthText = {
                            offsetX = 5,
                            posY = 0,
                            posX = 74.9,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -6.3,
                            posY = -12,
                            posX = 86.2,
                            justifyH = "LEFT",
                            offsetY = 8,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 20,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                    },
                    EnableTargetTarget = true,
                },
            },
            ["Orbit_PlayerBuffs"] = {
                [1] = {
                    IconLimit = 30,
                    Collapsed = false,
                    Spacing = 0,
                    Anchor = {
                        target = "OrbitActionBar5",
                        padding = 42,
                        edge = "RIGHT",
                        align = "TOP",
                    },
                    Rows = 1,
                    DisabledComponents = {
                        "Status",
                    },
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            overrides = {
                                FontSize = 14,
                            },
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            offsetX = 0,
                            justifyH = "RIGHT",
                            posY = -10,
                            posX = 10,
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                },
            },
            ["Orbit_TargetOfTargetFrame"] = {
                [100] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitTargetBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 100,
                },
            },
            ["Orbit_FocusBuffs"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusPower",
                        padding = 3,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    MaxRows = 2,
                    IconsPerRow = 8,
                    Scale = 100,
                },
            },
            ["Orbit_PlayerCastBar"] = {
                [1] = {
                    CastBarHeight = 35,
                    CastBarTextSize = 10,
                    CastBarWidth = 300,
                    SparkColorCurve = {
                        pins = {
                            {
                                color = { a = 0.263955146074295, r = 1, g = 1, b = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    Position = {
                        y = 135.65812463403,
                        x = 0,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    CastBarTimer = true,
                    CastBarText = true,
                    CastBarColorCurve = {
                        pins = {
                            {
                                color = { a = 1, r = 1, g = 0.7, b = 0 },
                                position = 0,
                            },
                        },
                    },
                },
            },
            ["Orbit_TargetCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 0,
                        edge = "TOP",
                    },
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_TargetBuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    Scale = 100,
                    Anchor = {
                        target = "OrbitTargetPower",
                        padding = 3,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    IconsPerRow = 8,
                },
            },
            ["Orbit_BossFrames"] = {
                [1] = {
                    DebuffSize = 32,
                    MaxDebuffs = 4,
                    Spacing = 24,
                    Anchor = false,
                    ComponentPositions = {
                        CastBar = {
                            posY = -29.26496219070707,
                            subComponents = {
                                Timer = {
                                    offsetX = 4,
                                    justifyH = "RIGHT",
                                    offsetY = 0,
                                    anchorX = "RIGHT",
                                    anchorY = "CENTER",
                                },
                                Text = {
                                    offsetX = 4,
                                    justifyH = "LEFT",
                                    offsetY = 0,
                                    anchorX = "LEFT",
                                    anchorY = "CENTER",
                                },
                            },
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = -9.846154207308631,
                            anchorX = "CENTER",
                            anchorY = "BOTTOM",
                        },
                        Debuffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 4,
                                MaxRows = 1,
                                PandemicGlowColorCurve = {
                                    pins = {
                                        {
                                            color = { a = 1, b = 0, g = 0.1882353127002716, r = 1 },
                                            position = 0.5891250838806241,
                                        },
                                    },
                                },
                                IconSize = 40,
                                FilterDensity = 2,
                                PandemicGlowType = 1,
                            },
                            posX = -95,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            posY = 0,
                            offsetX = 5,
                            posX = -52.98290634155273,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        HealthText = {
                            posY = 0,
                            offsetX = 5,
                            posX = 52.98290634155273,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 20,
                            },
                            offsetX = -2,
                            posX = 95,
                            posY = 0,
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            posY = 19.41880798339844,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                    },
                    CastBarHeight = 18,
                    PandemicGlowColorCurve = {
                        pins = {
                            {
                                color = { a = 1, b = 0, g = 0.1882353127002716, r = 1 },
                                position = 0.5891250838806241,
                            },
                        },
                    },
                    DisabledComponents = {
                        "Buffs",
                        "Status",
                    },
                    Width = 116,
                    DebuffPosition = "Left",
                    PandemicGlowType = 1,
                    CastBarPosition = "Below",
                    Position = {
                        y = 62.73932989297293,
                        x = -493.401727499577,
                        point = "RIGHT",
                    },
                    ReactionColour = false,
                    Scale = 100,
                    CastBarIcon = false,
                    Height = 39,
                },
            },
            ["Orbit_Portal"] = {
                [1] = {
                    Anchor = false,
                    Position = {
                        y = -118,
                        x = 11,
                        point = "TOPLEFT",
                    },
                },
            },
            ["Orbit_PlayerPetFrame"] = {
                [8] = {
                    Height = 22,
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 4,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 91,
                },
            },
            ["Orbit_TargetOfFocusFrame"] = {
                [101] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitFocusBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 100,
                },
            },
            ["Orbit_FocusPower"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    Height = 7,
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_Performance"] = {
                ["Orbit_Performance"] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 15,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                },
            },
        },
    },
    GlobalSettings = {
        IconBorderOffset = 5,
        TextScale = "Medium",
        BackdropColourCurve = {
            pins = {
                {
                    color = { a = 0.5, b = 0.08, g = 0.08, r = 0.08 },
                    position = 0,
                },
            },
        },
        HideWhenMounted = false,
        ClassColorBackground = false,
        IconBorderSize = 2,
        UnitFrameBackdropColourCurve = {
            pins = {
                {
                    color = { a = 0.5, b = 0.08, g = 0.08, r = 0.08 },
                    position = 0,
                },
            },
        },
        Texture = "Solid",
        OverlayTexture = "None",
        BackdropColour = { a = 0.7, b = 0.145, g = 0.145, r = 0.145 },
        BarColor = { a = 1, r = 0.2, g = 0.8, b = 0.2 },
        BorderColor = { a = 1, b = 0, g = 0, r = 0 },
        IconBorderColor = { a = 1, b = 0, g = 0, r = 0 },
        Font = "Barlow Condensed Bold",
        UseClassColors = true,
        BorderSize = 2,
        OverlayAllFrames = false,
        BarColorCurve = {
            pins = {
                {
                    color = { a = 1, b = 0.9333333969116211, g = 0.5333333611488342, r = 0.529411792755127 },
                    type = "class",
                    position = 0.617915081077845,
                },
            },
        },
        IconBorderStyle = "flat",
        FontOutline = "OUTLINE",
    },
}
