-- [ LOCALIZATION - COMMON ] -------------------------------------------------------------------------
-- CMN_ keys. Shared UI verbs and generic actions used across the addon.
-- To translate: add or extend your locale block below. Missing keys fall back to enUS.
local _, Orbit = ...

local LOCALE_STRINGS = {
    enUS = {
        CMN_NEXT                   = "Next",
        CMN_DONE                   = "Done",
        CMN_CANCEL                 = "Cancel",
        CMN_BACK                   = "\194\171 Back",
        CMN_APPLY                  = "Apply",
        CMN_CREATE                 = "Create",
        CMN_DELETE                 = "Delete",
        CMN_EXPORT                 = "Export",
        CMN_IMPORT                 = "Import",
        CMN_FACTORY_RESET          = "Factory Reset",
        CMN_RESET_TO_DEFAULTS      = "Reset to Defaults",
        CMN_RESET_ACCOUNT_SETTINGS = "Reset Account Settings",
        CMN_RESET_PLUGIN           = "Reset Plugin",
        CMN_RESET_PROFILE_TOOLTIP  = "Reset selected profile to defaults",
        CMN_COPY_PROFILE_TOOLTIP   = "Copy selected profile",
        CMN_ONLY_GLOBAL_RESET      = "Only the Global profile can be reset",
        CMN_DELETE_PROFILE_TOOLTIP = "Delete selected profile",
        CMN_CANNOT_DELETE_ACTIVE   = "Cannot delete active or Global profile",
        CMN_ICON_POSITION          = "Icon Position",
        CMN_ICON_LEFT              = "Left",
        CMN_ICON_RIGHT             = "Right",
        CMN_ICON_OFF               = "Off",
        CMN_HIDDEN_VALUE           = "—",
        CMN_FONT                   = "Font",
        CMN_SIZE                   = "Size",
        CMN_COLOR                  = "Color",
    },
    deDE = {
        CMN_NEXT                   = "Weiter",
        CMN_DONE                   = "Fertig",
        CMN_CANCEL                 = "Abbrechen",
        CMN_FACTORY_RESET          = "Auf Werkseinstellungen zurücksetzen",
        CMN_RESET_ACCOUNT_SETTINGS = "Account-Einstellungen zurücksetzen",
        CMN_RESET_PLUGIN           = "Plugin zurücksetzen",
        CMN_RESET_PROFILE_TOOLTIP  = "Ausgewähltes Profil auf Standardwerte zurücksetzen",
        CMN_ONLY_GLOBAL_RESET      = "Nur das globale Profil kann zurückgesetzt werden",
        CMN_DELETE_PROFILE_TOOLTIP = "Ausgewähltes Profil löschen",
        CMN_CANNOT_DELETE_ACTIVE   = "Aktives oder globales Profil kann nicht gelöscht werden",
    },
    frFR = {
        CMN_NEXT                   = "Suivant",
        CMN_DONE                   = "Terminé",
        CMN_CANCEL                 = "Annuler",
        CMN_FACTORY_RESET          = "Réinitialisation d'usine",
        CMN_RESET_ACCOUNT_SETTINGS = "Réinitialiser les paramètres du compte",
        CMN_RESET_PLUGIN           = "Réinitialiser le plugin",
        CMN_RESET_PROFILE_TOOLTIP  = "Réinitialiser le profil sélectionné aux valeurs par défaut",
        CMN_ONLY_GLOBAL_RESET      = "Seul le profil global peut être réinitialisé",
        CMN_DELETE_PROFILE_TOOLTIP = "Supprimer le profil sélectionné",
        CMN_CANNOT_DELETE_ACTIVE   = "Impossible de supprimer le profil actif ou global",
    },
    esES = {
        CMN_NEXT                   = "Siguiente",
        CMN_DONE                   = "Hecho",
        CMN_CANCEL                 = "Cancelar",
        CMN_FACTORY_RESET          = "Restablecimiento de fábrica",
        CMN_RESET_ACCOUNT_SETTINGS = "Restablecer ajustes de la cuenta",
        CMN_RESET_PLUGIN           = "Restablecer plugin",
        CMN_RESET_PROFILE_TOOLTIP  = "Restablecer el perfil seleccionado a valores predeterminados",
        CMN_ONLY_GLOBAL_RESET      = "Solo se puede restablecer el perfil Global",
        CMN_DELETE_PROFILE_TOOLTIP = "Eliminar el perfil seleccionado",
        CMN_CANNOT_DELETE_ACTIVE   = "No se puede eliminar el perfil activo o Global",
    },
    ptBR = {
        CMN_NEXT                   = "Próximo",
        CMN_DONE                   = "Concluído",
        CMN_CANCEL                 = "Cancelar",
        CMN_FACTORY_RESET          = "Restauração de Fábrica",
        CMN_RESET_ACCOUNT_SETTINGS = "Redefinir Configurações da Conta",
        CMN_RESET_PLUGIN           = "Redefinir Plugin",
        CMN_RESET_PROFILE_TOOLTIP  = "Redefinir perfil selecionado para os padrões",
        CMN_ONLY_GLOBAL_RESET      = "Apenas o perfil Global pode ser redefinido",
        CMN_DELETE_PROFILE_TOOLTIP = "Excluir perfil selecionado",
        CMN_CANNOT_DELETE_ACTIVE   = "Não é possível excluir o perfil ativo ou Global",
    },
    ruRU = {
        CMN_NEXT                   = "Далее",
        CMN_DONE                   = "Готово",
        CMN_CANCEL                 = "Отмена",
        CMN_FACTORY_RESET          = "Сброс до заводских настроек",
        CMN_RESET_ACCOUNT_SETTINGS = "Сбросить настройки аккаунта",
        CMN_RESET_PLUGIN           = "Сбросить плагин",
        CMN_RESET_PROFILE_TOOLTIP  = "Сбросить выбранный профиль по умолчанию",
        CMN_ONLY_GLOBAL_RESET      = "Только глобальный профиль может быть сброшен",
        CMN_DELETE_PROFILE_TOOLTIP = "Удалить выбранный профиль",
        CMN_CANNOT_DELETE_ACTIVE   = "Невозможно удалить активный или глобальный профиль",
    },
    koKR = {
        CMN_NEXT                   = "다음",
        CMN_DONE                   = "완료",
        CMN_CANCEL                 = "취소",
        CMN_FACTORY_RESET          = "공장 초기화",
        CMN_RESET_ACCOUNT_SETTINGS = "계정 설정 초기화",
        CMN_RESET_PLUGIN           = "플러그인 초기화",
        CMN_RESET_PROFILE_TOOLTIP  = "선택한 프로필을 기본값으로 초기화",
        CMN_ONLY_GLOBAL_RESET      = "글로벌 프로필만 초기화할 수 있습니다",
        CMN_DELETE_PROFILE_TOOLTIP = "선택한 프로필 삭제",
        CMN_CANNOT_DELETE_ACTIVE   = "활성 또는 글로벌 프로필은 삭제할 수 없습니다",
    },
    zhCN = {
        CMN_NEXT                   = "下一步",
        CMN_DONE                   = "完成",
        CMN_CANCEL                 = "取消",
        CMN_FACTORY_RESET          = "恢复出厂设置",
        CMN_RESET_ACCOUNT_SETTINGS = "重置账号设置",
        CMN_RESET_PLUGIN           = "重置插件",
        CMN_RESET_PROFILE_TOOLTIP  = "将选定配置文件重置为默认值",
        CMN_ONLY_GLOBAL_RESET      = "只有全局配置文件可以被重置",
        CMN_DELETE_PROFILE_TOOLTIP = "删除选定的配置文件",
        CMN_CANNOT_DELETE_ACTIVE   = "无法删除活动或全局配置文件",
    },
    zhTW = {
        CMN_NEXT                   = "下一步",
        CMN_DONE                   = "完成",
        CMN_CANCEL                 = "取消",
        CMN_FACTORY_RESET          = "恢復原廠設定",
        CMN_RESET_ACCOUNT_SETTINGS = "重置帳號設定",
        CMN_RESET_PLUGIN           = "重置外掛",
        CMN_RESET_PROFILE_TOOLTIP  = "將選定的設定檔重置為預設值",
        CMN_ONLY_GLOBAL_RESET      = "只有全域設定檔可以被重置",
        CMN_DELETE_PROFILE_TOOLTIP = "刪除選定的設定檔",
        CMN_CANNOT_DELETE_ACTIVE   = "無法刪除活動或全域設定檔",
    }
}
Orbit.Localization.Install(LOCALE_STRINGS, "Common")
