-- [ LOCALIZATION - PLUGIN MANAGER ]--------------------------------------------------
-- PLG_ keys. Strings specific to the Plugin Manager panel: section headers,
-- tri-state tooltips, spec-lock messages, reload prompts.
-- To translate: uncomment your locale block and mirror the keys from enUS.
-- Missing keys fall back to enUS automatically.
local _, Orbit = ...

local LOCALE_STRINGS = {
    enUS = {
        PLG_UNIT_FRAMES       = "Unit Frames",
        PLG_GROUP_FRAMES      = "Group Frames",
        PLG_COMBAT            = "Combat",
        PLG_UI                = "UI",
        PLG_TRI_BLIZZARD      = "Blizzard default frame will show.",
        PLG_TRI_ORBIT         = "Orbit replaces Blizzard frame.",
        PLG_TRI_BOTH_DISABLED = "Both Orbit and Blizzard frames disabled.",
        PLG_SPEC_LOCKED       = "Not available for your current specialization.",
        PLG_CONFLICT_DESC     = "Conflicting addon detected. Another addon is managing this element.",
        PLG_RELOAD_UI         = "Reload UI",
        PLG_RELOAD_UI_APPLY   = "Reload UI to Apply",
    },
    deDE = {
        PLG_UNIT_FRAMES       = "Einheitenfenster",
        PLG_GROUP_FRAMES      = "Gruppenfenster",
        PLG_COMBAT            = "Kampf",
        PLG_UI                = "UI",
        PLG_TRI_BLIZZARD      = "Standard-Blizzard-Fenster wird angezeigt.",
        PLG_TRI_ORBIT         = "Orbit ersetzt das Blizzard-Fenster.",
        PLG_TRI_BOTH_DISABLED = "Sowohl Orbit- als auch Blizzard-Fenster deaktiviert.",
        PLG_SPEC_LOCKED       = "Für deine aktuelle Spezialisierung nicht verfügbar.",
        PLG_RELOAD_UI         = "UI neu laden",
        PLG_RELOAD_UI_APPLY   = "UI neu laden zum Übernehmen",
    },
    frFR = {
        PLG_UNIT_FRAMES       = "Cadres d'unité",
        PLG_GROUP_FRAMES      = "Cadres de groupe",
        PLG_COMBAT            = "Combat",
        PLG_UI                = "Interface",
        PLG_TRI_BLIZZARD      = "Le cadre par défaut de Blizzard s'affichera.",
        PLG_TRI_ORBIT         = "Orbit remplace le cadre de Blizzard.",
        PLG_TRI_BOTH_DISABLED = "Les cadres d'Orbit et de Blizzard sont désactivés.",
        PLG_SPEC_LOCKED       = "Indisponible pour votre spécialisation actuelle.",
        PLG_RELOAD_UI         = "Recharger l'UI",
        PLG_RELOAD_UI_APPLY   = "Recharger l'UI pour appliquer",
    },
    esES = {
        PLG_UNIT_FRAMES       = "Marcos de unidad",
        PLG_GROUP_FRAMES      = "Marcos de grupo",
        PLG_COMBAT            = "Combate",
        PLG_UI                = "Interfaz",
        PLG_TRI_BLIZZARD      = "Se mostrará el marco predeterminado de Blizzard.",
        PLG_TRI_ORBIT         = "Orbit reemplaza el marco de Blizzard.",
        PLG_TRI_BOTH_DISABLED = "Ambos marcos, de Orbit y Blizzard, desactivados.",
        PLG_SPEC_LOCKED       = "No disponible para tu especialización actual.",
        PLG_RELOAD_UI         = "Recargar UI",
        PLG_RELOAD_UI_APPLY   = "Recargar UI para aplicar",
    },
    ptBR = {
        PLG_UNIT_FRAMES       = "Quadros de Unidade",
        PLG_GROUP_FRAMES      = "Quadros de Grupo",
        PLG_COMBAT            = "Combate",
        PLG_UI                = "Interface",
        PLG_TRI_BLIZZARD      = "O quadro padrão da Blizzard será exibido.",
        PLG_TRI_ORBIT         = "O Orbit substitui o quadro da Blizzard.",
        PLG_TRI_BOTH_DISABLED = "Ambos os quadros, Orbit e Blizzard, desativados.",
        PLG_SPEC_LOCKED       = "Não disponível para sua especialização atual.",
        PLG_RELOAD_UI         = "Recarregar UI",
        PLG_RELOAD_UI_APPLY   = "Recarregar UI para Aplicar",
    },
    ruRU = {
        PLG_UNIT_FRAMES       = "Рамки юнитов",
        PLG_GROUP_FRAMES      = "Групповые рамки",
        PLG_COMBAT            = "Бой",
        PLG_UI                = "Интерфейс",
        PLG_TRI_BLIZZARD      = "Будет отображаться стандартная рамка Blizzard.",
        PLG_TRI_ORBIT         = "Orbit заменяет рамку Blizzard.",
        PLG_TRI_BOTH_DISABLED = "Рамки Orbit и Blizzard отключены.",
        PLG_SPEC_LOCKED       = "Недоступно для вашей текущей специализации.",
        PLG_RELOAD_UI         = "Перезагрузить UI",
        PLG_RELOAD_UI_APPLY   = "Перезагрузить UI для применения",
    },
    koKR = {
        PLG_UNIT_FRAMES       = "유닛 프레임",
        PLG_GROUP_FRAMES      = "그룹 프레임",
        PLG_COMBAT            = "전투",
        PLG_UI                = "UI",
        PLG_TRI_BLIZZARD      = "기본 블리자드 프레임이 표시됩니다.",
        PLG_TRI_ORBIT         = "Orbit이 블리자드 프레임을 대체합니다.",
        PLG_TRI_BOTH_DISABLED = "Orbit 및 블리자드 프레임 모두 비활성화됨.",
        PLG_SPEC_LOCKED       = "현재 전문화에서는 사용할 수 없습니다.",
        PLG_RELOAD_UI         = "UI 다시 불러오기",
        PLG_RELOAD_UI_APPLY   = "적용하려면 UI 다시 불러오기",
    },
    zhCN = {
        PLG_UNIT_FRAMES       = "单位框体",
        PLG_GROUP_FRAMES      = "队伍框体",
        PLG_COMBAT            = "战斗",
        PLG_UI                = "界面",
        PLG_TRI_BLIZZARD      = "将显示暴雪默认框体。",
        PLG_TRI_ORBIT         = "Orbit 替换暴雪框体。",
        PLG_TRI_BOTH_DISABLED = "Orbit 和暴雪框体均已禁用。",
        PLG_SPEC_LOCKED       = "当前专精下不可用。",
        PLG_RELOAD_UI         = "重载界面",
        PLG_RELOAD_UI_APPLY   = "重载界面以应用",
    },
    zhTW = {
        PLG_UNIT_FRAMES       = "單位框架",
        PLG_GROUP_FRAMES      = "隊伍框架",
        PLG_COMBAT            = "戰鬥",
        PLG_UI                = "介面",
        PLG_TRI_BLIZZARD      = "將顯示暴雪預設框架。",
        PLG_TRI_ORBIT         = "Orbit 替換暴雪框架。",
        PLG_TRI_BOTH_DISABLED = "Orbit 和暴雪框架均已停用。",
        PLG_SPEC_LOCKED       = "目前專精下不可用。",
        PLG_RELOAD_UI         = "重載介面",
        PLG_RELOAD_UI_APPLY   = "重載介面以套用",
    }
}
Orbit.Localization.Install(LOCALE_STRINGS, "PluginManager")
