-- [ LOCALIZATION - SLASH COMMANDS ] -----------------------------------------------------------------
-- CMD_ keys. Strings printed by /orbit subcommands, confirmation popup text and
-- button labels, minimap button tooltip lines.
-- Keys ending in _F are format strings passed to :format() at the call site.
-- To translate: uncomment your locale block and mirror the keys from enUS.
-- Missing keys fall back to enUS automatically.
local _, Orbit = ...

local LOCALE_STRINGS = {
    enUS = {
        CMD_HARD_RESET_WARNING   = "|cFFFF0000DANGER|r\n\nYou are about to FACTORY RESET Orbit.\n\nAll profiles, settings, and data will be wiped.\nThe UI will reload immediately.\n\nAre you sure?",
        CMD_RESET_ACCOUNT_WARNING = "|cFFFF0000WARNING|r\n\nYou are about to reset all Account Settings to defaults.\n\nThis includes class colors, reaction colors, recent colors, QoL toggles, and spec profile mappings.\n\nThe UI will reload immediately.\n\nAre you sure?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000WARNING|r\n\nYou are about to reset '%s' to default settings and position.\n\nThis cannot be undone.\n\nAre you sure?",
        CMD_HELP_HEADER          = "Commands:",
        CMD_HELP_ORBIT           = "|cFF00FFFF/orbit|r \226\128\148 Toggle Edit Mode + Settings",
        CMD_HELP_HELP            = "|cFF00FFFF/orbit help|r \226\128\148 This list",
        CMD_HELP_VERSION         = "|cFF00FFFF/orbit version|r \226\128\148 Version, profile, and system info",
        CMD_HELP_LIST            = "|cFF00FFFF/orbit list|r \226\128\148 List all plugins with ON/OFF status",
        CMD_HELP_PLUGINS         = "|cFF00FFFF/orbit plugins|r \226\128\148 Open Plugin Manager",
        CMD_HELP_PROFILE_SHOW    = "|cFF00FFFF/orbit profile|r \226\128\148 Show current profile",
        CMD_HELP_PROFILE_SWITCH  = "|cFF00FFFF/orbit profile <name>|r \226\128\148 Switch to profile",
        CMD_HELP_FRAMES          = "|cFF00FFFF/orbit frames <name>|r \226\128\148 Show frame position/visibility",
        CMD_HELP_INSPECT         = "|cFF00FFFF/orbit inspect <name>|r \226\128\148 Dump plugin settings",
        CMD_HELP_REFRESH         = "|cFF00FFFF/orbit refresh <name>|r \226\128\148 Force re-apply plugin",
        CMD_HELP_RESET           = "|cFF00FFFF/orbit reset|r \226\128\148 Reset Account Settings",
        CMD_HELP_RESET_PLUGIN    = "|cFF00FFFF/orbit reset <name>|r \226\128\148 Reset a plugin to defaults",
        CMD_HELP_VE              = "|cFF00FFFF/orbit ve|r \226\128\148 Open Visibility Engine",
        CMD_HELP_VE_RESET        = "|cFF00FFFF/orbit ve reset|r \226\128\148 Reset VE to defaults",
        CMD_HELP_WHATSNEW        = "|cFF00FFFF/orbit whatsnew|r \226\128\148 Show changelog",
        CMD_HELP_HARDRESET       = "|cFF00FFFF/orbit hardreset|r \226\128\148 Factory reset (wipes everything)",
        CMD_HELP_TRACKED_FLUSH   = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Delete all Tracked containers for current spec",
        CMD_TRACKED_USAGE        = "Usage: /orbit tracked flush",
        CMD_REFRESH_USAGE        = "Usage: /orbit refresh <plugin_name>",
        CMD_VERSION_LABEL        = "Version:",
        CMD_PROFILE_LABEL        = "Profile:",
        CMD_SPEC_LABEL           = "Spec:",
        CMD_PLUGINS_LABEL        = "Plugins:",
        CMD_COMBAT_LABEL         = "Combat:",
        CMD_WOW_BUILD_LABEL      = "WoW Build:",
        CMD_FRAMES_USAGE         = "Usage: /orbit frames <plugin_name>",
        CMD_INSPECT_USAGE        = "Usage: /orbit inspect <plugin_name>",
        CMD_SEE_LIST             = "Use |cFF00FFFF/orbit list|r to see plugin names.",
        CMD_ANCHOR_USAGE         = "Usage: /orbit anchor <FrameName>  (e.g. /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F    = "No frame named '%s' in _G",
        CMD_ANCHOR_GRAPH_MISSING = "FrameAnchor / AnchorGraph not loaded",
        CMD_ANCHOR_HEADER_F      = "|cFFFFD100%s|r  skipped=%s",
        CMD_ANCHOR_PHYSICAL_F    = "  physical: %s edge=%s",
        CMD_ANCHOR_PHYSICAL_NONE = "  physical: |cFFFF0000NONE|r",
        CMD_ANCHOR_SETPOINT_F    = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F     = "  logical:  %s edge=%s",
        CMD_ANCHOR_SAVED_F       = "  saved Anchor: target=%s edge=%s",
        CMD_ANCHOR_FALLBACK_F    = "    fallback=%s",
        CMD_ANCHOR_ANCESTRY_F    = "    ancestry=%s",
        CMD_ANCHOR_ANCESTRY_NIL  = "    ancestry=|cFFFF0000nil|r  (re-drag in edit mode to populate)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000not in _G|r",
        CMD_ANCHOR_PROBE_F       = "    %s %s: exists, skipped=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (no parent)",
        CMD_ANCHOR_POSITION_F    = "  saved Position: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED      = "  no saved Anchor/Position (using defaultPosition)",
        CMD_UNKNOWN_COMMAND_F    = "Unknown command: %s. Type |cFF00FFFF/orbit help|r for a list.",
        CMD_MINIMAP_LEFT_CLICK   = "|cFF00FF00Left-click|r Edit Mode + Orbit Options",
        CMD_MINIMAP_RIGHT_CLICK  = "|cFFFFFF00Right-click|r Advanced Options",
        CMD_PORTAL_SCAN_DONE     = "Portal: M+ cache cleared and dock refreshed!",
        CMD_PORTAL_HEADER        = "|cFF00FFFFOrbit Portal Commands:|r",
        CMD_PORTAL_HELP_SCAN     = "  |cFF00FFFF/orbit portal scan|r \226\128\148 Clear M+ cache and refresh dock",
        CMD_WHATSNEW_TITLE       = "|cFFFFD100Orbit: What's New|r",
        CMD_WHATSNEW_THANKS      = "Thanks for your support! - MoONSHO7",
        CMD_DISCORD_TITLE        = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY         = "Join the discord to request features, report bugs\nor ask for help from the community.",
        CMD_OPTIONS_BUTTON_LABEL = "Orbit Options",
        CMD_LANG_CURRENT_F       = "Current language: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F      = "Override active: |cFFFFD100%s|r (client locale: %s)",
        CMD_LANG_AVAILABLE       = "Available locales:",
        CMD_LANG_USAGE           = "Usage: |cFF00FFFF/orbit lang <locale>|r or |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F       = "Unknown locale '%s'. Type |cFF00FFFF/orbit lang|r to list available locales.",
        CMD_LANG_SET_F           = "Language override set to |cFFFFD100%s|r. Please Reload UI.",
        CMD_LANG_CLEARED         = "Language override cleared. Please Reload UI.",
        CMD_STATUS_ON              = "ON",
        CMD_STATUS_OFF             = "OFF",
        CMD_FRAME_SHOWN            = "shown",
        CMD_FRAME_HIDDEN           = "hidden",
        CMD_FRAME_UNANCHORED       = "unanchored",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    deDE = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000GEFAHR|r\n\nDu bist dabei, Orbit auf WERKSEINSTELLUNGEN zurückzusetzen.\n\nAlle Profile, Einstellungen und Daten werden gelöscht.\nDas UI wird sofort neu geladen.\n\nBist du sicher?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000WARNUNG|r\n\nDu bist dabei, alle Account-Einstellungen auf Standardwerte zurückzusetzen.\n\nDies beinhaltet Klassenfarben, Reaktionsfarben, aktuelle Farben, QoL-Optionen und Profilzuweisungen für Spezifikationen.\n\nDas UI wird sofort neu geladen.\n\nBist du sicher?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000WARNUNG|r\n\nDu bist dabei, '%s' auf Standardeinstellungen und -position zurückzusetzen.\n\nDies kann nicht rückgängig gemacht werden.\n\nBist du sicher?",
        CMD_HELP_HEADER            = "Befehle:",
        CMD_HELP_ORBIT             = "/orbit - Bearbeitungsmodus + Einstellungen umschalten",
        CMD_HELP_HELP              = "/orbit help - Diese Liste",
        CMD_HELP_VERSION           = "/orbit version - Version, Profil und Systeminfos",
        CMD_HELP_LIST              = "/orbit list - Alle Plugins mit AN/AUS-Status auflisten",
        CMD_HELP_PLUGINS           = "/orbit plugins - Plugin Manager öffnen",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - Zeige aktuelles Profil",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <name> - Zu Profil wechseln",
        CMD_HELP_FRAMES            = "/orbit frames <name> - Zeige Fensterposition/Sichtbarkeit",
        CMD_HELP_INSPECT           = "/orbit inspect <name> - Plugin-Einstellungen ausgeben",
        CMD_HELP_REFRESH           = "/orbit refresh <name> - Plugin-Anwendung erzwingen",
        CMD_HELP_RESET             = "/orbit reset - Account-Einstellungen zurücksetzen",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <name> - Ein Plugin auf Standardwerte zurücksetzen",
        CMD_HELP_VE                = "/orbit ve - Visibility Engine öffnen",
        CMD_HELP_VE_RESET          = "/orbit ve reset - VE auf Standardwerte zurücksetzen",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - Changelog anzeigen",
        CMD_HELP_HARDRESET         = "/orbit hardreset - Werkseinstellungen (löscht alles)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Alle Tracked-Container für die aktuelle Spezialisierung löschen",
        CMD_TRACKED_USAGE          = "Verwendung: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "Verwendung: /orbit refresh <plugin_name>",
        CMD_VERSION_LABEL          = "Version:",
        CMD_PROFILE_LABEL          = "Profil:",
        CMD_SPEC_LABEL             = "Spezialisierung:",
        CMD_PLUGINS_LABEL          = "Plugins:",
        CMD_COMBAT_LABEL           = "Kampf:",
        CMD_WOW_BUILD_LABEL        = "WoW-Build:",
        CMD_FRAMES_USAGE           = "Verwendung: /orbit frames <plugin_name>",
        CMD_INSPECT_USAGE          = "Verwendung: /orbit inspect <plugin_name>",
        CMD_SEE_LIST               = "Verwende |cFF00FFFF/orbit list|r um Plugin-Namen zu sehen.",
        CMD_ANCHOR_USAGE           = "Verwendung: /orbit anchor <FrameName>  (z. B. /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "Kein Fenster mit dem Namen '%s' in _G",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph nicht geladen",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  übersprungen=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  physisch: %s Kante=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  physisch: |cFFFF0000KEINE|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  logisch:  %s Kante=%s",
        CMD_ANCHOR_SAVED_F         = "  gespeicherter Anker: Ziel=%s Kante=%s",
        CMD_ANCHOR_FALLBACK_F      = "    Ausweich=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    Abstammung=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    Abstammung=|cFFFF0000nil|r  (im Bearbeitungsmodus erneut ziehen zum Befüllen)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000nicht in _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: vorhanden, übersprungen=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (Eltern=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (kein Eltern-Element)",
        CMD_ANCHOR_POSITION_F      = "  gespeicherte Position: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  kein gespeicherter Anker / keine gespeicherte Position (defaultPosition wird verwendet)",
        CMD_UNKNOWN_COMMAND_F      = "Unbekannter Befehl: %s. Tippe |cFF00FFFF/orbit help|r für eine Liste.",
        CMD_MINIMAP_LEFT_CLICK     = "Linksklick für Bearbeitungsmodus + Orbit Optionen",
        CMD_MINIMAP_RIGHT_CLICK    = "Rechtsklick für Erweiterte Optionen",
        CMD_PORTAL_SCAN_DONE       = "Portal: M+-Cache geleert und Ablage aktualisiert!",
        CMD_PORTAL_HEADER          = "|cFF00FFFFOrbit Portal-Befehle:|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 M+-Cache leeren und Ablage aktualisieren",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit: Neuigkeiten|r",
        CMD_WHATSNEW_THANKS        = "Danke für deine Unterstützung! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "Tritt dem Discord bei, um Funktionen vorzuschlagen, Fehler zu melden\noder die Community um Hilfe zu bitten.",
        CMD_OPTIONS_BUTTON_LABEL   = "Orbit Optionen",
        CMD_LANG_CURRENT_F         = "Aktuelle Sprache: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "Überschreibung aktiv: |cFFFFD100%s|r (Client-Sprache: %s)",
        CMD_LANG_AVAILABLE         = "Verfügbare Sprachen:",
        CMD_LANG_USAGE             = "Verwendung: |cFF00FFFF/orbit lang <locale>|r oder |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "Unbekannte Sprache '%s'. Tippe |cFF00FFFF/orbit lang|r, um verfügbare Sprachen aufzulisten.",
        CMD_LANG_SET_F             = "Sprachüberschreibung auf |cFFFFD100%s|r gesetzt. Bitte UI neu laden.",
        CMD_LANG_CLEARED           = "Sprachüberschreibung aufgehoben. Bitte UI neu laden.",
        CMD_STATUS_ON              = "AN",
        CMD_STATUS_OFF             = "AUS",
        CMD_FRAME_SHOWN            = "sichtbar",
        CMD_FRAME_HIDDEN           = "verborgen",
        CMD_FRAME_UNANCHORED       = "ohne Verankerung",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    frFR = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000DANGER|r\n\nVous êtes sur le point de RÉINITIALISER Orbit.\n\nTous les profils, paramètres et données seront effacés.\nL'interface sera rechargée immédiatement.\n\nÊtes-vous sûr(e) ?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000AVERTISSEMENT|r\n\nVous êtes sur le point de réinitialiser tous les paramètres du compte.\n\nCeci inclut les couleurs de classe, de réaction, les couleurs récentes, les options de QoL et les associations de profil par spécialisation.\n\nL'interface sera rechargée immédiatement.\n\nÊtes-vous sûr(e) ?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000AVERTISSEMENT|r\n\nVous êtes sur le point de réinitialiser '%s' à ses paramètres et sa position par défaut.\n\nCette action est irréversible.\n\nÊtes-vous sûr(e) ?",
        CMD_HELP_HEADER            = "Commandes :",
        CMD_HELP_ORBIT             = "/orbit - Basculer le mode d'édition + paramètres",
        CMD_HELP_HELP              = "/orbit help - Cette liste",
        CMD_HELP_VERSION           = "/orbit version - Informations sur la version, le profil et le système",
        CMD_HELP_LIST              = "/orbit list - Lister tous les plugins avec leur statut",
        CMD_HELP_PLUGINS           = "/orbit plugins - Ouvrir le gestionnaire de plugins",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - Afficher le profil actuel",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <nom> - Passer au profil indiqué",
        CMD_HELP_FRAMES            = "/orbit frames <nom> - Afficher la position/visibilité du cadre",
        CMD_HELP_INSPECT           = "/orbit inspect <nom> - Vider les paramètres du plugin",
        CMD_HELP_REFRESH           = "/orbit refresh <nom> - Forcer l'application du plugin",
        CMD_HELP_RESET             = "/orbit reset - Réinitialiser les paramètres du compte",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <nom> - Réinitialiser un plugin à ses valeurs par défaut",
        CMD_HELP_VE                = "/orbit ve - Ouvrir le Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - Réinitialiser le VE",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - Afficher le journal des modifications",
        CMD_HELP_HARDRESET         = "/orbit hardreset - Réinitialisation d'usine (efface tout)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Supprimer tous les conteneurs Tracked de la spécialisation actuelle",
        CMD_TRACKED_USAGE          = "Utilisation : /orbit tracked flush",
        CMD_REFRESH_USAGE          = "Utilisation : /orbit refresh <nom_plugin>",
        CMD_VERSION_LABEL          = "Version :",
        CMD_PROFILE_LABEL          = "Profil :",
        CMD_SPEC_LABEL             = "Spécialisation :",
        CMD_PLUGINS_LABEL          = "Plugins :",
        CMD_COMBAT_LABEL           = "Combat :",
        CMD_WOW_BUILD_LABEL        = "Build WoW :",
        CMD_FRAMES_USAGE           = "Utilisation : /orbit frames <nom_plugin>",
        CMD_INSPECT_USAGE          = "Utilisation : /orbit inspect <nom_plugin>",
        CMD_SEE_LIST               = "Utilisez |cFF00FFFF/orbit list|r pour voir les noms des plugins.",
        CMD_ANCHOR_USAGE           = "Utilisation : /orbit anchor <NomCadre>  (ex. /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "Aucun cadre nommé '%s' dans _G",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph non chargé",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  ignoré=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  physique : %s bord=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  physique : |cFFFF0000AUCUN|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint : %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  logique :  %s bord=%s",
        CMD_ANCHOR_SAVED_F         = "  Ancrage enregistré : cible=%s bord=%s",
        CMD_ANCHOR_FALLBACK_F      = "    repli=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ascendance=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ascendance=|cFFFF0000nil|r  (re-glissez en mode Édition pour la renseigner)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s : |cFFFF0000absent de _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s : existe, ignoré=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (aucun parent)",
        CMD_ANCHOR_POSITION_F      = "  Position enregistrée : %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  aucun Ancrage/Position enregistré (utilisation de defaultPosition)",
        CMD_UNKNOWN_COMMAND_F      = "Commande inconnue : %s. Tapez |cFF00FFFF/orbit help|r pour afficher la liste.",
        CMD_MINIMAP_LEFT_CLICK     = "Clic gauche : Mode édition + Options Orbit",
        CMD_MINIMAP_RIGHT_CLICK    = "Clic droit : Options avancées",
        CMD_PORTAL_SCAN_DONE       = "Portal : cache M+ effacé et dock actualisé !",
        CMD_PORTAL_HEADER          = "|cFF00FFFFCommandes Orbit Portal :|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 Effacer le cache M+ et actualiser le dock",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit : Nouveautés|r",
        CMD_WHATSNEW_THANKS        = "Merci pour votre soutien ! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "Rejoignez le Discord pour demander des fonctionnalités, signaler des bugs\nou demander de l'aide à la communauté.",
        CMD_OPTIONS_BUTTON_LABEL   = "Options Orbit",
        CMD_LANG_CURRENT_F         = "Langue actuelle : |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "Remplacement actif : |cFFFFD100%s|r (locale du client : %s)",
        CMD_LANG_AVAILABLE         = "Locales disponibles :",
        CMD_LANG_USAGE             = "Utilisation : |cFF00FFFF/orbit lang <locale>|r ou |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "Locale inconnue '%s'. Tapez |cFF00FFFF/orbit lang|r pour lister les locales disponibles.",
        CMD_LANG_SET_F             = "Remplacement de langue défini sur |cFFFFD100%s|r. Veuillez recharger l'UI.",
        CMD_LANG_CLEARED           = "Remplacement de langue supprimé. Veuillez recharger l'UI.",
        CMD_STATUS_ON              = "ACTIVÉ",
        CMD_STATUS_OFF             = "DÉSACTIVÉ",
        CMD_FRAME_SHOWN            = "visible",
        CMD_FRAME_HIDDEN           = "masqué",
        CMD_FRAME_UNANCHORED       = "sans ancrage",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    esES = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000PELIGRO|r\n\nEstás a punto de restaurar Orbit de FÁBRICA.\n\nTodos los perfiles, ajustes y datos se borrarán.\nLa interfaz se recargará inmediatamente.\n\n¿Estás seguro?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000ADVERTENCIA|r\n\nEstás a punto de restablecer los ajustes de la cuenta.\n\nEsto incluye colores de clase, colores de reacción, colores recientes, opciones de QoL y asignaciones de perfil por especialización.\n\nLa interfaz se recargará inmediatamente.\n\n¿Estás seguro?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000ADVERTENCIA|r\n\nEstás a punto de restablecer '%s' a su configuración y posición predeterminadas.\n\nEsto no se puede deshacer.\n\n¿Estás seguro?",
        CMD_HELP_HEADER            = "Comandos:",
        CMD_HELP_ORBIT             = "/orbit - Alternar Modo Edición + Ajustes",
        CMD_HELP_HELP              = "/orbit help - Esta lista",
        CMD_HELP_VERSION           = "/orbit version - Información de versión, perfil y sistema",
        CMD_HELP_LIST              = "/orbit list - Lista de plugins con su estado ENCENDIDO/APAGADO",
        CMD_HELP_PLUGINS           = "/orbit plugins - Abrir el Gestor de Plugins",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - Mostrar el perfil actual",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <nombre> - Cambiar al perfil indicado",
        CMD_HELP_FRAMES            = "/orbit frames <nombre> - Mostrar posición/visibilidad del marco",
        CMD_HELP_INSPECT           = "/orbit inspect <nombre> - Volcar los ajustes del plugin",
        CMD_HELP_REFRESH           = "/orbit refresh <nombre> - Forzar aplicación del plugin",
        CMD_HELP_RESET             = "/orbit reset - Restablecer Ajustes de la Cuenta",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <nombre> - Restablecer un plugin",
        CMD_HELP_VE                = "/orbit ve - Abrir el Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - Restablecer el VE",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - Mostrar el registro de cambios",
        CMD_HELP_HARDRESET         = "/orbit hardreset - Restablecimiento de fábrica (borra todo)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Elimina todos los contenedores de Tracked de la especialización actual",
        CMD_TRACKED_USAGE          = "Uso: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "Uso: /orbit refresh <nombre_plugin>",
        CMD_VERSION_LABEL          = "Versión:",
        CMD_PROFILE_LABEL          = "Perfil:",
        CMD_SPEC_LABEL             = "Especialización:",
        CMD_PLUGINS_LABEL          = "Plugins:",
        CMD_COMBAT_LABEL           = "Combate:",
        CMD_WOW_BUILD_LABEL        = "Build de WoW:",
        CMD_FRAMES_USAGE           = "Uso: /orbit frames <nombre_plugin>",
        CMD_INSPECT_USAGE          = "Uso: /orbit inspect <nombre_plugin>",
        CMD_SEE_LIST               = "Usa |cFF00FFFF/orbit list|r para ver los nombres de los plugins.",
        CMD_ANCHOR_USAGE           = "Uso: /orbit anchor <NombreMarco>  (p. ej. /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "No hay ningún marco llamado '%s' en _G",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph no cargado",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  omitido=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  físico: %s borde=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  físico: |cFFFF0000NINGUNO|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  lógico:  %s borde=%s",
        CMD_ANCHOR_SAVED_F         = "  Anclaje guardado: destino=%s borde=%s",
        CMD_ANCHOR_FALLBACK_F      = "    alternativa=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ascendencia=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ascendencia=|cFFFF0000nil|r  (vuelve a arrastrar en el Modo Edición para rellenar)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000no está en _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: existe, omitido=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (padre=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (sin padre)",
        CMD_ANCHOR_POSITION_F      = "  Posición guardada: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  sin Anclaje/Posición guardados (usando defaultPosition)",
        CMD_UNKNOWN_COMMAND_F      = "Comando desconocido: %s. Escribe |cFF00FFFF/orbit help|r para ver la lista.",
        CMD_MINIMAP_LEFT_CLICK     = "Clic izquierdo: Modo Edición + Opciones de Orbit",
        CMD_MINIMAP_RIGHT_CLICK    = "Clic derecho: Opciones avanzadas",
        CMD_PORTAL_SCAN_DONE       = "Portal: ¡caché de M+ borrada y dock actualizado!",
        CMD_PORTAL_HEADER          = "|cFF00FFFFComandos de Orbit Portal:|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 Borrar la caché de M+ y actualizar el dock",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit: Novedades|r",
        CMD_WHATSNEW_THANKS        = "¡Gracias por tu apoyo! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "Únete al Discord para solicitar funciones, informar de errores\no pedir ayuda a la comunidad.",
        CMD_OPTIONS_BUTTON_LABEL   = "Opciones de Orbit",
        CMD_LANG_CURRENT_F         = "Idioma actual: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "Anulación activa: |cFFFFD100%s|r (idioma del cliente: %s)",
        CMD_LANG_AVAILABLE         = "Idiomas disponibles:",
        CMD_LANG_USAGE             = "Uso: |cFF00FFFF/orbit lang <idioma>|r o |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "Idioma desconocido '%s'. Escribe |cFF00FFFF/orbit lang|r para ver los idiomas disponibles.",
        CMD_LANG_SET_F             = "Anulación de idioma establecida en |cFFFFD100%s|r. Recarga la UI.",
        CMD_LANG_CLEARED           = "Anulación de idioma eliminada. Recarga la UI.",
        CMD_STATUS_ON              = "ACTIVADO",
        CMD_STATUS_OFF             = "DESACTIVADO",
        CMD_FRAME_SHOWN            = "visible",
        CMD_FRAME_HIDDEN           = "oculto",
        CMD_FRAME_UNANCHORED       = "sin anclar",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    ptBR = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000PERIGO|r\n\nVocê está prestes a restaurar o Orbit de FÁBRICA.\n\nTodos os perfis, configurações e dados serão apagados.\nA interface será recarregada imediatamente.\n\nTem certeza?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000AVISO|r\n\nVocê está prestes a redefinir as configurações da Conta.\n\nIsso inclui cores de classe, cores de reação, cores recentes, opções de QoL e mapeamentos de perfil de especialização.\n\nA interface será recarregada imediatamente.\n\nTem certeza?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000AVISO|r\n\nVocê está prestes a redefinir '%s' para as configurações e posições padrão.\n\nIsso não pode ser desfeito.\n\nTem certeza?",
        CMD_HELP_HEADER            = "Comandos:",
        CMD_HELP_ORBIT             = "/orbit - Alternar Modo de Edição + Configurações",
        CMD_HELP_HELP              = "/orbit help - Esta lista",
        CMD_HELP_VERSION           = "/orbit version - Informações da versão, perfil e sistema",
        CMD_HELP_LIST              = "/orbit list - Listar todos os plugins e seu status",
        CMD_HELP_PLUGINS           = "/orbit plugins - Abrir Gerenciador de Plugins",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - Mostrar o perfil atual",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <nome> - Mudar para o perfil indicado",
        CMD_HELP_FRAMES            = "/orbit frames <nome> - Mostrar posição/visibilidade do quadro",
        CMD_HELP_INSPECT           = "/orbit inspect <nome> - Despejar configurações do plugin",
        CMD_HELP_REFRESH           = "/orbit refresh <nome> - Forçar a aplicação do plugin",
        CMD_HELP_RESET             = "/orbit reset - Redefinir Configurações da Conta",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <nome> - Redefinir um plugin para os padrões",
        CMD_HELP_VE                = "/orbit ve - Abrir Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - Redefinir o VE para os padrões",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - Mostrar histórico de atualizações",
        CMD_HELP_HARDRESET         = "/orbit hardreset - Redefinição de fábrica (apaga tudo)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Exclui todos os contêineres do Tracked da especialização atual",
        CMD_TRACKED_USAGE          = "Uso: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "Uso: /orbit refresh <nome_do_plugin>",
        CMD_VERSION_LABEL          = "Versão:",
        CMD_PROFILE_LABEL          = "Perfil:",
        CMD_SPEC_LABEL             = "Especialização:",
        CMD_PLUGINS_LABEL          = "Plugins:",
        CMD_COMBAT_LABEL           = "Combate:",
        CMD_WOW_BUILD_LABEL        = "Build do WoW:",
        CMD_FRAMES_USAGE           = "Uso: /orbit frames <nome_do_plugin>",
        CMD_INSPECT_USAGE          = "Uso: /orbit inspect <nome_do_plugin>",
        CMD_SEE_LIST               = "Use |cFF00FFFF/orbit list|r para ver nomes de plugins.",
        CMD_ANCHOR_USAGE           = "Uso: /orbit anchor <NomeDoQuadro>  (ex.: /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "Nenhum quadro chamado '%s' em _G",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph não carregado",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  ignorado=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  físico: %s borda=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  físico: |cFFFF0000NENHUM|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  lógico:  %s borda=%s",
        CMD_ANCHOR_SAVED_F         = "  Âncora salva: alvo=%s borda=%s",
        CMD_ANCHOR_FALLBACK_F      = "    reserva=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ascendência=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ascendência=|cFFFF0000nil|r  (rearraste no modo de edição para preencher)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000não está em _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: existe, ignorado=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (pai=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (sem pai)",
        CMD_ANCHOR_POSITION_F      = "  Posição salva: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  nenhuma Âncora/Posição salva (usando defaultPosition)",
        CMD_UNKNOWN_COMMAND_F      = "Comando desconhecido: %s. Digite |cFF00FFFF/orbit help|r para obter uma lista.",
        CMD_MINIMAP_LEFT_CLICK     = "Clique com o botão esquerdo para Modo de Edição + Opções do Orbit",
        CMD_MINIMAP_RIGHT_CLICK    = "Clique com o botão direito para Opções Avançadas",
        CMD_PORTAL_SCAN_DONE       = "Portal: cache de M+ limpo e dock atualizado!",
        CMD_PORTAL_HEADER          = "|cFF00FFFFComandos do Orbit Portal:|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 Limpa o cache de M+ e atualiza o dock",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit: Novidades|r",
        CMD_WHATSNEW_THANKS        = "Obrigado pelo seu apoio! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "Entre no discord para solicitar recursos, relatar bugs\nou pedir ajuda à comunidade.",
        CMD_OPTIONS_BUTTON_LABEL   = "Opções do Orbit",
        CMD_LANG_CURRENT_F         = "Idioma atual: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "Substituição ativa: |cFFFFD100%s|r (localidade do cliente: %s)",
        CMD_LANG_AVAILABLE         = "Localidades disponíveis:",
        CMD_LANG_USAGE             = "Uso: |cFF00FFFF/orbit lang <localidade>|r ou |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "Localidade desconhecida '%s'. Digite |cFF00FFFF/orbit lang|r para listar as localidades disponíveis.",
        CMD_LANG_SET_F             = "Substituição de idioma definida para |cFFFFD100%s|r. Por favor, recarregue a UI.",
        CMD_LANG_CLEARED           = "Substituição de idioma removida. Por favor, recarregue a UI.",
        CMD_STATUS_ON              = "LIGADO",
        CMD_STATUS_OFF             = "DESLIGADO",
        CMD_FRAME_SHOWN            = "visível",
        CMD_FRAME_HIDDEN           = "oculto",
        CMD_FRAME_UNANCHORED       = "sem âncora",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    ruRU = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000ОПАСНОСТЬ|r\n\nВы собираетесь СБРОСИТЬ Orbit ДО ЗАВОДСКИХ НАСТРОЕК.\n\nВсе профили, настройки и данные будут удалены.\nUI перезагрузится немедленно.\n\nВы уверены?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000ВНИМАНИЕ|r\n\nВы собираетесь сбросить настройки аккаунта по умолчанию.\n\nЭто включает цвета классов, цвета реакций, последние цвета, переключатели QoL и привязки профилей к специализациям.\n\nUI перезагрузится немедленно.\n\nВы уверены?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000ВНИМАНИЕ|r\n\nВы собираетесь сбросить '%s' к настройкам и положению по умолчанию.\n\nЭто действие нельзя отменить.\n\nВы уверены?",
        CMD_HELP_HEADER            = "Команды:",
        CMD_HELP_ORBIT             = "/orbit - Включить режим редактирования + настройки",
        CMD_HELP_HELP              = "/orbit help - Этот список",
        CMD_HELP_VERSION           = "/orbit version - Информация о версии, профиле и системе",
        CMD_HELP_LIST              = "/orbit list - Показать все плагины и их статус (ВКЛ/ВЫКЛ)",
        CMD_HELP_PLUGINS           = "/orbit plugins - Открыть менеджер плагинов",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - Показать текущий профиль",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <имя> - Переключиться на профиль",
        CMD_HELP_FRAMES            = "/orbit frames <имя> - Показать позицию/видимость рамки",
        CMD_HELP_INSPECT           = "/orbit inspect <имя> - Дамп настроек плагина",
        CMD_HELP_REFRESH           = "/orbit refresh <имя> - Принудительно применить плагин",
        CMD_HELP_RESET             = "/orbit reset - Сбросить настройки аккаунта",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <имя> - Сбросить плагин по умолчанию",
        CMD_HELP_VE                = "/orbit ve - Открыть Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - Сбросить VE по умолчанию",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - Показать список изменений",
        CMD_HELP_HARDRESET         = "/orbit hardreset - Заводской сброс (удаление всего)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 Удалить все контейнеры Tracked для текущей специализации",
        CMD_TRACKED_USAGE          = "Использование: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "Использование: /orbit refresh <имя_плагина>",
        CMD_VERSION_LABEL          = "Версия:",
        CMD_PROFILE_LABEL          = "Профиль:",
        CMD_SPEC_LABEL             = "Специализация:",
        CMD_PLUGINS_LABEL          = "Плагины:",
        CMD_COMBAT_LABEL           = "Бой:",
        CMD_WOW_BUILD_LABEL        = "Сборка WoW:",
        CMD_FRAMES_USAGE           = "Использование: /orbit frames <имя_плагина>",
        CMD_INSPECT_USAGE          = "Использование: /orbit inspect <имя_плагина>",
        CMD_SEE_LIST               = "Используйте |cFF00FFFF/orbit list|r, чтобы увидеть имена плагинов.",
        CMD_ANCHOR_USAGE           = "Использование: /orbit anchor <ИмяРамки>  (напр. /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "В _G нет рамки с именем «%s»",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph не загружены",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  skipped=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  physical: %s edge=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  physical: |cFFFF0000NONE|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  logical:  %s edge=%s",
        CMD_ANCHOR_SAVED_F         = "  сохранённая привязка: target=%s edge=%s",
        CMD_ANCHOR_FALLBACK_F      = "    fallback=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ancestry=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ancestry=|cFFFF0000nil|r  (перетащите заново в режиме редактирования для заполнения)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000нет в _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: существует, skipped=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (нет родителя)",
        CMD_ANCHOR_POSITION_F      = "  сохранённая позиция: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  нет сохранённой привязки/позиции (используется defaultPosition)",
        CMD_UNKNOWN_COMMAND_F      = "Неизвестная команда: %s. Введите |cFF00FFFF/orbit help|r для просмотра списка.",
        CMD_MINIMAP_LEFT_CLICK     = "ЛКМ — режим редактирования + настройки Orbit",
        CMD_MINIMAP_RIGHT_CLICK    = "ПКМ — расширенные настройки",
        CMD_PORTAL_SCAN_DONE       = "Portal: кэш М+ очищен, панель обновлена!",
        CMD_PORTAL_HEADER          = "|cFF00FFFFКоманды Orbit Portal:|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 Очистить кэш М+ и обновить панель",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit: что нового|r",
        CMD_WHATSNEW_THANKS        = "Спасибо за поддержку! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "Присоединяйтесь к Discord, чтобы предлагать функции, сообщать об ошибках\nили получить помощь от сообщества.",
        CMD_OPTIONS_BUTTON_LABEL   = "Параметры Orbit",
        CMD_LANG_CURRENT_F         = "Текущий язык: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "Активно переопределение: |cFFFFD100%s|r (язык клиента: %s)",
        CMD_LANG_AVAILABLE         = "Доступные языки:",
        CMD_LANG_USAGE             = "Использование: |cFF00FFFF/orbit lang <язык>|r или |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "Неизвестный язык «%s». Введите |cFF00FFFF/orbit lang|r для списка доступных языков.",
        CMD_LANG_SET_F             = "Переопределение языка установлено на |cFFFFD100%s|r. Пожалуйста, перезагрузите UI.",
        CMD_LANG_CLEARED           = "Переопределение языка сброшено. Пожалуйста, перезагрузите UI.",
        CMD_STATUS_ON              = "ВКЛ",
        CMD_STATUS_OFF             = "ВЫКЛ",
        CMD_FRAME_SHOWN            = "виден",
        CMD_FRAME_HIDDEN           = "скрыт",
        CMD_FRAME_UNANCHORED       = "без привязки",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    koKR = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000위험|r\n\nOrbit을 공장 초기화하려고 합니다.\n\n모든 프로필, 설정 및 데이터가 지워집니다.\nUI가 즉시 재로드됩니다.\n\n계속하시겠습니까?",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000경고|r\n\n모든 계정 설정을 기본값으로 초기화하려고 합니다.\n\n여기에는 직업 색상, 반응 색상, 최근 색상, QoL 설정 및 전문화 프로필 매핑이 포함됩니다.\n\nUI가 즉시 재로드됩니다.\n\n계속하시겠습니까?",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000경고|r\n\n'%s'을(를) 기본 설정 및 위치로 초기화하려고 합니다.\n\n이 작업은 실행 취소할 수 없습니다.\n\n계속하시겠습니까?",
        CMD_HELP_HEADER            = "명령어:",
        CMD_HELP_ORBIT             = "/orbit - 편집 모드 + 설정 전환",
        CMD_HELP_HELP              = "/orbit help - 이 목록",
        CMD_HELP_VERSION           = "/orbit version - 버전, 프로필 및 시스템 정보",
        CMD_HELP_LIST              = "/orbit list - 켜짐/꺼짐 상태의 모든 플러그인 목록",
        CMD_HELP_PLUGINS           = "/orbit plugins - 플러그인 관리자 열기",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - 현재 프로필 표시",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <이름> - 프로필로 전환",
        CMD_HELP_FRAMES            = "/orbit frames <이름> - 프레임 위치/가시성 표시",
        CMD_HELP_INSPECT           = "/orbit inspect <이름> - 플러그인 설정 덤프",
        CMD_HELP_REFRESH           = "/orbit refresh <이름> - 플러그인 강제 재적용",
        CMD_HELP_RESET             = "/orbit reset - 계정 설정 초기화",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <이름> - 플러그인을 기본값으로 초기화",
        CMD_HELP_VE                = "/orbit ve - Visibility Engine 열기",
        CMD_HELP_VE_RESET          = "/orbit ve reset - VE를 기본값으로 초기화",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - 변경 내역 표시",
        CMD_HELP_HARDRESET         = "/orbit hardreset - 공장 초기화 (모두 지우기)",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 현재 전문화의 모든 Tracked 컨테이너 삭제",
        CMD_TRACKED_USAGE          = "사용법: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "사용법: /orbit refresh <플러그인_이름>",
        CMD_VERSION_LABEL          = "버전:",
        CMD_PROFILE_LABEL          = "프로필:",
        CMD_SPEC_LABEL             = "전문화:",
        CMD_PLUGINS_LABEL          = "플러그인:",
        CMD_COMBAT_LABEL           = "전투:",
        CMD_WOW_BUILD_LABEL        = "WoW 빌드:",
        CMD_FRAMES_USAGE           = "사용법: /orbit frames <플러그인_이름>",
        CMD_INSPECT_USAGE          = "사용법: /orbit inspect <플러그인_이름>",
        CMD_SEE_LIST               = "플러그인 이름을 보려면 |cFF00FFFF/orbit list|r를 사용하세요.",
        CMD_ANCHOR_USAGE           = "사용법: /orbit anchor <프레임이름>  (예: /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "_G에 '%s'(이)라는 이름의 프레임이 없음",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph가 로드되지 않음",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  skipped=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  물리: %s edge=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  물리: |cFFFF0000없음|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  논리:  %s edge=%s",
        CMD_ANCHOR_SAVED_F         = "  저장된 Anchor: target=%s edge=%s",
        CMD_ANCHOR_FALLBACK_F      = "    fallback=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ancestry=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ancestry=|cFFFF0000nil|r  (편집 모드에서 다시 드래그하여 채우세요)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000_G에 없음|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: 존재함, skipped=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (부모 없음)",
        CMD_ANCHOR_POSITION_F      = "  저장된 Position: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  저장된 Anchor/Position 없음 (defaultPosition 사용)",
        CMD_UNKNOWN_COMMAND_F      = "알 수 없는 명령: %s. 목록을 보려면 |cFF00FFFF/orbit help|r를 입력하세요.",
        CMD_MINIMAP_LEFT_CLICK     = "좌클릭: 편집 모드 + Orbit 옵션",
        CMD_MINIMAP_RIGHT_CLICK    = "우클릭: 고급 옵션",
        CMD_PORTAL_SCAN_DONE       = "Portal: 쐐기돌 캐시를 지우고 독을 새로 고침!",
        CMD_PORTAL_HEADER          = "|cFF00FFFFOrbit Portal 명령어:|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 쐐기돌 캐시를 지우고 독 새로 고침",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit: 변경 내역|r",
        CMD_WHATSNEW_THANKS        = "성원해 주셔서 감사합니다! - MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100디스코드|r",
        CMD_DISCORD_BODY           = "디스코드에 가입하여 기능을 요청하고 버그를 신고하거나\n커뮤니티에 도움을 요청하세요.",
        CMD_OPTIONS_BUTTON_LABEL   = "Orbit 옵션",
        CMD_LANG_CURRENT_F         = "현재 언어: |cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "재정의 활성화됨: |cFFFFD100%s|r (클라이언트 로캘: %s)",
        CMD_LANG_AVAILABLE         = "사용 가능한 로캘:",
        CMD_LANG_USAGE             = "사용법: |cFF00FFFF/orbit lang <로캘>|r 또는 |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "알 수 없는 로캘 '%s'. |cFF00FFFF/orbit lang|r을 입력하면 사용 가능한 로캘이 표시됩니다.",
        CMD_LANG_SET_F             = "언어 재정의가 |cFFFFD100%s|r(으)로 설정됨. UI를 다시 로드해 주세요.",
        CMD_LANG_CLEARED           = "언어 재정의가 해제됨. UI를 다시 로드해 주세요.",
        CMD_STATUS_ON              = "켜짐",
        CMD_STATUS_OFF             = "꺼짐",
        CMD_FRAME_SHOWN            = "표시됨",
        CMD_FRAME_HIDDEN           = "숨김",
        CMD_FRAME_UNANCHORED       = "고정 안 됨",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    zhCN = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000危险|r\n\n您即将对 Orbit 进行恢复出厂设置。\n\n所有配置文件、设置和数据将被擦除。\n界面将立即重载。\n\n您确定吗？",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000警告|r\n\n您即将重置所有账号设置至默认值。\n\n这包括职业颜色、反应颜色、最近使用的颜色、QoL开关，以及专精与配置文件的映射。\n\n界面将立即重载。\n\n您确定吗？",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000警告|r\n\n您即将将 '%s' 重置为默认设置和位置。\n\n此操作无法撤销。\n\n您确定吗？",
        CMD_HELP_HEADER            = "命令：",
        CMD_HELP_ORBIT             = "/orbit - 切换编辑模式 + 设置",
        CMD_HELP_HELP              = "/orbit help - 此列表",
        CMD_HELP_VERSION           = "/orbit version - 版本、配置文件和系统信息",
        CMD_HELP_LIST              = "/orbit list - 列出所有插件及其启用/禁用状态",
        CMD_HELP_PLUGINS           = "/orbit plugins - 打开插件管理器",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - 显示当前配置文件",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <名称> - 切换至该配置文件",
        CMD_HELP_FRAMES            = "/orbit frames <名称> - 显示框体位置/可见性",
        CMD_HELP_INSPECT           = "/orbit inspect <名称> - 导出插件设置",
        CMD_HELP_REFRESH           = "/orbit refresh <名称> - 强制重新应用插件",
        CMD_HELP_RESET             = "/orbit reset - 重置账号设置",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <名称> - 将某插件重置为默认值",
        CMD_HELP_VE                = "/orbit ve - 打开 Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - 重置 VE 至默认值",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - 显示更新日志",
        CMD_HELP_HARDRESET         = "/orbit hardreset - 恢复出厂设置（擦除一切）",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 删除当前专精的所有 Tracked 容器",
        CMD_TRACKED_USAGE          = "用法：/orbit tracked flush",
        CMD_REFRESH_USAGE          = "用法：/orbit refresh <插件名称>",
        CMD_VERSION_LABEL          = "版本：",
        CMD_PROFILE_LABEL          = "配置文件：",
        CMD_SPEC_LABEL             = "专精：",
        CMD_PLUGINS_LABEL          = "插件：",
        CMD_COMBAT_LABEL           = "战斗状态：",
        CMD_WOW_BUILD_LABEL        = "WoW 版本：",
        CMD_FRAMES_USAGE           = "用法：/orbit frames <插件名称>",
        CMD_INSPECT_USAGE          = "用法：/orbit inspect <插件名称>",
        CMD_SEE_LIST               = "使用 |cFF00FFFF/orbit list|r 查看插件名称。",
        CMD_ANCHOR_USAGE           = "用法：/orbit anchor <框体名称>  （例如 /orbit anchor OrbitPlayerPower）",
        CMD_ANCHOR_NO_FRAME_F      = "_G 中没有名为 '%s' 的框体",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph 未加载",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  skipped=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  physical: %s edge=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  physical: |cFFFF0000NONE|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  logical:  %s edge=%s",
        CMD_ANCHOR_SAVED_F         = "  saved Anchor: target=%s edge=%s",
        CMD_ANCHOR_FALLBACK_F      = "    fallback=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ancestry=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ancestry=|cFFFF0000nil|r  （在编辑模式中重新拖动以填充）",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000not in _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: exists, skipped=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (no parent)",
        CMD_ANCHOR_POSITION_F      = "  saved Position: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  没有已保存的 Anchor/Position（使用 defaultPosition）",
        CMD_UNKNOWN_COMMAND_F      = "未知命令: %s。输入 |cFF00FFFF/orbit help|r 查看列表。",
        CMD_MINIMAP_LEFT_CLICK     = "左键单击：编辑模式 + Orbit 选项",
        CMD_MINIMAP_RIGHT_CLICK    = "右键单击：高级选项",
        CMD_PORTAL_SCAN_DONE       = "Portal：M+ 缓存已清除，停靠栏已刷新！",
        CMD_PORTAL_HEADER          = "|cFF00FFFFOrbit Portal 命令：|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 清除 M+ 缓存并刷新停靠栏",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit：更新内容|r",
        CMD_WHATSNEW_THANKS        = "感谢你的支持！- MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "加入 Discord 以请求新功能、报告错误，\n或向社区寻求帮助。",
        CMD_OPTIONS_BUTTON_LABEL   = "Orbit 选项",
        CMD_LANG_CURRENT_F         = "当前语言：|cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "覆盖已生效：|cFFFFD100%s|r（客户端区域设置：%s）",
        CMD_LANG_AVAILABLE         = "可用区域设置：",
        CMD_LANG_USAGE             = "用法：|cFF00FFFF/orbit lang <区域设置>|r 或 |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "未知的区域设置 '%s'。输入 |cFF00FFFF/orbit lang|r 查看可用区域设置列表。",
        CMD_LANG_SET_F             = "语言覆盖已设置为 |cFFFFD100%s|r。请重新加载界面。",
        CMD_LANG_CLEARED           = "语言覆盖已清除。请重新加载界面。",
        CMD_STATUS_ON              = "开",
        CMD_STATUS_OFF             = "关",
        CMD_FRAME_SHOWN            = "显示",
        CMD_FRAME_HIDDEN           = "隐藏",
        CMD_FRAME_UNANCHORED       = "未锚定",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    },
    zhTW = {
        CMD_HARD_RESET_WARNING     = "|cFFFF0000危險|r\n\n您即將對 Orbit 進行恢復原廠設定。\n\n所有設定檔、設定和資料將被抹除。\n介面將立即重載。\n\n您確定嗎？",
        CMD_RESET_ACCOUNT_WARNING  = "|cFFFF0000警告|r\n\n您即將重置所有帳號設定至預設值。\n\n這包括職業顏色、反應顏色、最近使用的顏色、QoL開關，以及專精與設定檔的映射。\n\n介面將立即重載。\n\n您確定嗎？",
        CMD_RESET_PLUGIN_WARNING_F = "|cFFFF0000警告|r\n\n您即將將 '%s' 重置為預設設定和位置。\n\n此操作無法復原。\n\n您確定嗎？",
        CMD_HELP_HEADER            = "指令:",
        CMD_HELP_ORBIT             = "/orbit - 切換編輯模式 + 設定",
        CMD_HELP_HELP              = "/orbit help - 此列表",
        CMD_HELP_VERSION           = "/orbit version - 版本、設定檔和系統資訊",
        CMD_HELP_LIST              = "/orbit list - 列出所有外掛及其啟用/停用狀態",
        CMD_HELP_PLUGINS           = "/orbit plugins - 開啟外掛管理器",
        CMD_HELP_PROFILE_SHOW      = "/orbit profile - 顯示目前設定檔",
        CMD_HELP_PROFILE_SWITCH    = "/orbit profile <名稱> - 切換至該設定檔",
        CMD_HELP_FRAMES            = "/orbit frames <名稱> - 顯示框架位置/可見性",
        CMD_HELP_INSPECT           = "/orbit inspect <名稱> - 匯出外掛設定",
        CMD_HELP_REFRESH           = "/orbit refresh <名稱> - 強制重新套用外掛",
        CMD_HELP_RESET             = "/orbit reset - 重置帳號設定",
        CMD_HELP_RESET_PLUGIN      = "/orbit reset <名稱> - 將某外掛重置為預設值",
        CMD_HELP_VE                = "/orbit ve - 開啟 Visibility Engine",
        CMD_HELP_VE_RESET          = "/orbit ve reset - 重置 VE 至預設值",
        CMD_HELP_WHATSNEW          = "/orbit whatsnew - 顯示更新日誌",
        CMD_HELP_HARDRESET         = "/orbit hardreset - 恢復原廠設定（抹除一切）",
        CMD_HELP_TRACKED_FLUSH     = "|cFF00FFFF/orbit tracked flush|r \226\128\148 刪除目前專精的所有 Tracked 容器",
        CMD_TRACKED_USAGE          = "用法: /orbit tracked flush",
        CMD_REFRESH_USAGE          = "用法: /orbit refresh <外掛名稱>",
        CMD_VERSION_LABEL          = "版本:",
        CMD_PROFILE_LABEL          = "設定檔:",
        CMD_SPEC_LABEL             = "專精:",
        CMD_PLUGINS_LABEL          = "外掛:",
        CMD_COMBAT_LABEL           = "戰鬥狀態:",
        CMD_WOW_BUILD_LABEL        = "WoW 版本:",
        CMD_FRAMES_USAGE           = "用法: /orbit frames <外掛名稱>",
        CMD_INSPECT_USAGE          = "用法: /orbit inspect <外掛名稱>",
        CMD_SEE_LIST               = "使用 |cFF00FFFF/orbit list|r 查看外掛名稱。",
        CMD_ANCHOR_USAGE           = "用法: /orbit anchor <框架名稱>  (例如 /orbit anchor OrbitPlayerPower)",
        CMD_ANCHOR_NO_FRAME_F      = "_G 中沒有名為 '%s' 的框架",
        CMD_ANCHOR_GRAPH_MISSING   = "FrameAnchor / AnchorGraph 未載入",
        CMD_ANCHOR_HEADER_F        = "|cFFFFD100%s|r  skipped=%s",
        CMD_ANCHOR_PHYSICAL_F      = "  physical: %s edge=%s",
        CMD_ANCHOR_PHYSICAL_NONE   = "  physical: |cFFFF0000NONE|r",
        CMD_ANCHOR_SETPOINT_F      = "    SetPoint: %s @ %s (%.0f, %.0f)",
        CMD_ANCHOR_LOGICAL_F       = "  logical:  %s edge=%s",
        CMD_ANCHOR_SAVED_F         = "  saved Anchor: target=%s edge=%s",
        CMD_ANCHOR_FALLBACK_F      = "    fallback=%s",
        CMD_ANCHOR_ANCESTRY_F      = "    ancestry=%s",
        CMD_ANCHOR_ANCESTRY_NIL    = "    ancestry=|cFFFF0000nil|r  (在編輯模式中重新拖曳以填入)",
        CMD_ANCHOR_PROBE_MISSING_F = "    %s %s: |cFFFF0000not in _G|r",
        CMD_ANCHOR_PROBE_F         = "    %s %s: exists, skipped=%s%s",
        CMD_ANCHOR_PROBE_PARENT_F  = " (parent=%s)",
        CMD_ANCHOR_PROBE_NO_PARENT = " (no parent)",
        CMD_ANCHOR_POSITION_F      = "  saved Position: %s (%s, %s)",
        CMD_ANCHOR_NO_SAVED        = "  無已儲存的 Anchor/Position（使用 defaultPosition）",
        CMD_UNKNOWN_COMMAND_F      = "未知指令: %s。輸入 |cFF00FFFF/orbit help|r 查看列表。",
        CMD_MINIMAP_LEFT_CLICK     = "左鍵點擊：編輯模式 + Orbit 選項",
        CMD_MINIMAP_RIGHT_CLICK    = "右鍵點擊：進階選項",
        CMD_PORTAL_SCAN_DONE       = "Portal：M+ 快取已清除，停靠欄已重新整理！",
        CMD_PORTAL_HEADER          = "|cFF00FFFFOrbit Portal 指令：|r",
        CMD_PORTAL_HELP_SCAN       = "  |cFF00FFFF/orbit portal scan|r \226\128\148 清除 M+ 快取並重新整理停靠欄",
        CMD_WHATSNEW_TITLE         = "|cFFFFD100Orbit：更新內容|r",
        CMD_WHATSNEW_THANKS        = "感謝你的支持！- MoONSHO7",
        CMD_DISCORD_TITLE          = "|cFFFFD100Discord|r",
        CMD_DISCORD_BODY           = "加入 Discord 來提出功能需求、回報錯誤\n或向社群尋求協助。",
        CMD_OPTIONS_BUTTON_LABEL   = "Orbit 選項",
        CMD_LANG_CURRENT_F         = "目前語言：|cFFFFD100%s|r",
        CMD_LANG_OVERRIDE_F        = "覆寫已啟用：|cFFFFD100%s|r（用戶端地區：%s）",
        CMD_LANG_AVAILABLE         = "可用的地區設定：",
        CMD_LANG_USAGE             = "用法: |cFF00FFFF/orbit lang <地區設定>|r 或 |cFF00FFFF/orbit lang auto|r",
        CMD_LANG_INVALID_F         = "未知的地區設定 '%s'。輸入 |cFF00FFFF/orbit lang|r 以列出可用的地區設定。",
        CMD_LANG_SET_F             = "語言覆寫已設為 |cFFFFD100%s|r。請重新載入介面。",
        CMD_LANG_CLEARED           = "語言覆寫已清除。請重新載入介面。",
        CMD_STATUS_ON              = "開啟",
        CMD_STATUS_OFF             = "關閉",
        CMD_FRAME_SHOWN            = "顯示",
        CMD_FRAME_HIDDEN           = "隱藏",
        CMD_FRAME_UNANCHORED       = "未錨定",
        CMD_FRAME_LABEL_MAIN       = "frame",
        CMD_FRAME_LABEL_ESSENTIAL  = "essentialAnchor",
        CMD_FRAME_LABEL_UTILITY    = "utilityAnchor",
        CMD_FRAME_LABEL_BUFFICON   = "buffIconAnchor",
    }
}
Orbit.Localization.Install(LOCALE_STRINGS, "SlashCmds")
