import re
import os

# [ CONFIGURATION ] -----------------------------------------------------------------

CHANGELOG_PATH = "CHANGELOG.md"
OUTPUT_PATH = "Orbit/Core/Config/ChangelogData.lua"

# [ PARSING ] ----------------------------------------------------------------------

def parse_changelog():
    if not os.path.exists(CHANGELOG_PATH):
        print(f"Error: {CHANGELOG_PATH} not found.")
        return None

    with open(CHANGELOG_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find the latest version section (excluding Unreleased)
    # Matches ## [v.v.v] - YYYY-MM-DD or ## [@project-version@] - @project-date-iso@
    version_matches = list(re.finditer(r'## \[(.*?)\] - (\d{4}-\d{2}-\d{2}|@project-date-iso@)', content))
    if not version_matches:
        print("Error: No version entries found in CHANGELOG.md.")
        return None

    latest_match = version_matches[0]
    version = latest_match.group(1)
    
    # Get content between this version and the next version (or end of file)
    start_pos = latest_match.end()
    end_pos = version_matches[1].start() if len(version_matches) > 1 else len(content)
    section_content = content[start_pos:end_pos].strip()

    entries = []
    
    # Parse sub-headers (Message, Added, Fixed, etc.)
    sub_headers = re.split(r'###\s+(.*)', section_content)
    
    # sub_headers[0] is everything before the first ###
    for i in range(1, len(sub_headers), 2):
        header = sub_headers[i].strip()
        body = sub_headers[i+1].strip()
        
        # Clean up bullet points for Lua string
        body_lua = body.replace('"', '\\"').replace('\n', '\\n')
        # Replace leading bullet points with dots for cleaner look if preferred, 
        # but here we'll keep them or standardize.
        
        entries.append({
            "title": header,
            "body": body_lua
        })

    return version, entries

# [ LUA GENERATION ] ---------------------------------------------------------------

def generate_lua(version, entries):
    lua_content = f"""-- [ GENERATED CHANGELOG DATA ] ----------------------------------------------------
-- This file is automatically generated by update_changelog.py. Do not edit.

local _, addonTable = ...
local Orbit = addonTable

Orbit.LatestChangelogVersion = "{version}"

Orbit.WHATS_NEW_ENTRIES = {{
"""
    for entry in entries:
        lua_content += f'    {{ title = "{entry["title"]}", body = "{entry["body"]}" }},\n'
    
    lua_content += "}\n"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(lua_content)
    print(f"Generated {OUTPUT_PATH}")

# [ MAIN ] -------------------------------------------------------------------------

if __name__ == "__main__":
    result = parse_changelog()
    if result:
        ver, ents = result
        generate_lua(ver, ents)
