import re
import os

# [ CONFIGURATION ] -----------------------------------------------------------------

CHANGELOG_PATH = "CHANGELOG.md"
OUTPUT_PATH = "Orbit/Core/Config/ChangelogData.lua"
START_MARKER = "[start]"
END_MARKER = "[end]"
VERSION_TOKEN = "@project-version@"

# [ PARSING ] ----------------------------------------------------------------------

def parse_changelog():
    if not os.path.exists(CHANGELOG_PATH):
        print(f"Error: {CHANGELOG_PATH} not found.")
        return None

    with open(CHANGELOG_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    start_match = re.search(r'^\s*\[start\]\s*$', content, re.MULTILINE | re.IGNORECASE)
    end_match = re.search(r'^\s*\[end\]\s*$', content, re.MULTILINE | re.IGNORECASE)
    if not start_match or not end_match or end_match.start() <= start_match.end():
        print(f"Error: {START_MARKER} / {END_MARKER} markers not found or out of order in CHANGELOG.md.")
        return None

    section_content = content[start_match.end():end_match.start()].strip()
    version = VERSION_TOKEN

    entries = []
    
    # Parse sub-headers (Message, Added, Fixed, etc.)
    sub_headers = re.split(r'###\s+(.*)', section_content)
    
    # sub_headers[0] is everything before the first ###
    for i in range(1, len(sub_headers), 2):
        header = sub_headers[i].strip()
        body = sub_headers[i+1].strip()
        
        # Clean up bullet points for Lua string
        body_lua = body.replace('"', '\\"').replace('\n', '\\n')
        # Replace leading bullet points with dots for cleaner look if preferred, 
        # but here we'll keep them or standardize.
        
        entries.append({
            "title": header,
            "body": body_lua
        })

    return version, entries

# [ LUA GENERATION ] ---------------------------------------------------------------

def generate_lua(version, entries):
    lua_content = f"""-- [ GENERATED CHANGELOG DATA ] ----------------------------------------------------
-- This file is automatically generated by update_changelog.py. Do not edit.

local _, addonTable = ...
local Orbit = addonTable

Orbit.LatestChangelogVersion = "{version}"

Orbit.WHATS_NEW_ENTRIES = {{
"""
    for entry in entries:
        lua_content += f'    {{ title = "{entry["title"]}", body = "{entry["body"]}" }},\n'
    
    lua_content += "}\n"

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(lua_content)
    print(f"Generated {OUTPUT_PATH}")

# [ MAIN ] -------------------------------------------------------------------------

if __name__ == "__main__":
    result = parse_changelog()
    if result:
        ver, ents = result
        generate_lua(ver, ents)
