local _, Orbit = ...

-- [ DEFAULT PROFILE ]-------------------------------------------------------------------------------
Orbit.Profile = Orbit.Profile or {}
Orbit.Profile.defaults = {
    Layouts = {
        ["Orbit"] = {
            ["Orbit_FocusCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    CastBarWidth = 200,
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_QueueStatus"] = {
                ["Orbit_QueueStatus"] = {
                    Anchor = false,
                    Position = {
                        y = -4,
                        x = -343,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_FocusFrame"] = {
                [3] = {
                    EnableFocusTarget = true,
                    EnableFocusPower = true,
                    ReactionColour = false,
                    PortraitStyle = "3d",
                    DisabledComponents = {
                        "Portrait",
                    },
                    Width = 160,
                    Is3D = true,
                    PortraitBorder = true,
                    PortraitShape = "square",
                    Position = {
                        y = -273.5,
                        x = -376.9,
                        point = "RIGHT",
                    },
                    Anchor = false,
                    PortraitScale = 125,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -2,
                            posY = 14.04274130149705,
                            posX = 81.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 5.923077103654316,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.86327362060547,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 19.96581840515137,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            posY = 0,
                            posX = 74.86327362060547,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -7.923077103654316,
                            posY = -12.11966419784274,
                            posX = 87.78635072425979,
                            justifyH = "LEFT",
                            offsetY = 7.846154207308631,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Portrait = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 4,
                            anchorY = "CENTER",
                        },
                    },
                    Height = 40,
                },
            },
            ["Orbit_CooldownViewer"] = {
                [1] = {
                    IconSize = 120,
                    aspectRatio = "4:3",
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            offsetX = 2,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    IconLimit = 12,
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = -225,
                        x = 0,
                        point = "CENTER",
                    },
                },
                [2] = {
                    IconSize = 90,
                    aspectRatio = "4:3",
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -11,
                            offsetX = 1,
                            posX = -17,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    IconLimit = 8,
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = -284,
                        x = 0,
                        point = "CENTER",
                    },
                },
                [3] = {
                    IconLimit = 10,
                    Opacity = 100,
                    IconPadding = 1,
                    aspectRatio = "4:3",
                    Position = {
                        y = -146,
                        x = -1,
                        point = "CENTER",
                    },
                    IconSize = 100,
                    PandemicGlowType = 1,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            offsetX = 2,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    Anchor = false,
                },
                [4] = {
                    Anchor = false,
                    aspectRatio = "1:1",
                    Position = {
                        y = -0.2734985765385964,
                        x = -31.99999546675529,
                        point = "CENTER",
                    },
                },
                [20] = {
                },
            },
            ["Orbit_BagBar"] = {
                ["Orbit_BagBar"] = {
                    Anchor = {
                        target = "OrbitMicroMenuContainer",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Opacity = 100,
                    Scale = 100,
                },
            },
            ["Orbit_Status"] = {
                [1] = {
                    Height = 16,
                    Position = "TOP",
                },
            },
            ["Orbit_TargetDebuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitTargetCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                },
            },
            ["Orbit_FocusDebuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    Anchor = {
                        target = "OrbitFocusCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Scale = 100,
                    IconsPerRow = 8,
                },
            },
            ["Orbit_TalkingHead"] = {
                ["Orbit_TalkingHead"] = {
                    Anchor = false,
                    Scale = 60,
                    Position = {
                        y = -123,
                        x = 0,
                        point = "TOP",
                    },
                },
            },
            ["Orbit_RaidFrames"] = {
                [1] = {
                    GroupsPerRow = 6,
                    DisabledComponents = {
                        "DefensiveIcon",
                        "CrowdControlIcon",
                        "Status",
                    },
                    ShowHealthValue = false,
                    Width = 100,
                    DispelFrequency = 0.2,
                    Anchor = false,
                    MemberSpacing = 2,
                    GroupSpacing = 2,
                    Orientation = "Horizontal",
                    Position = {
                        y = -118.2,
                        x = 97.9,
                        point = "TOPLEFT",
                    },
                    ComponentPositions = {
                        ResIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Debuffs = {
                            posY = -9.0,
                            offsetX = 1,
                            overrides = {
                                MaxIcons = 2,
                                MaxRows = 3,
                                IconSize = 10,
                            },
                            posX = -45.1,
                            justifyH = "LEFT",
                            offsetY = 1,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            posY = 20.0,
                            offsetX = 8,
                            overrides = {
                                Scale = 0.8,
                            },
                            posX = -42.1,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        DefensiveIcon = {
                            offsetX = 2,
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Status = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        SummonIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        CrowdControlIcon = {
                            offsetX = 0,
                            offsetY = 2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            overrides = {
                                FontSize = 10,
                                HealthTextMode = "percent_short",
                                ShowHealthValue = false,
                            },
                            posY = -10.1,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 9.8,
                            anchorX = "CENTER",
                            anchorY = "BOTTOM",
                        },
                        MarkerIcon = {
                            posY = 21.0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = -1,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        PrivateAuraAnchor = {
                            posY = 0,
                            offsetX = 0,
                            overrides = {
                                Scale = 1,
                            },
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Name = {
                            posY = 10.0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 10,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        RoleIcon = {
                            posY = 18.0,
                            offsetX = 2,
                            overrides = {
                                Scale = 0.7,
                            },
                            posX = 48.1,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        PhaseIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            posY = -15.0,
                            offsetX = 1,
                            overrides = {
                                MaxIcons = 4,
                                MaxRows = 1,
                                IconSize = 15,
                            },
                            posX = 27.1,
                            justifyH = "RIGHT",
                            offsetY = 1,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        ReadyCheckIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        MainTankIcon = {
                            posY = 19.4,
                            offsetX = 17.0,
                            overrides = {
                                Scale = 0.6,
                            },
                            posX = -33.0,
                            justifyH = "LEFT",
                            offsetY = 0.5,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                    },
                    Height = 40,
                },
            },
            ["Orbit_TargetPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_MicroMenu"] = {
                ["Orbit_MicroMenu"] = {
                    Anchor = false,
                    Padding = -5,
                    Rows = 1,
                    Position = {
                        y = 1,
                        x = 0,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_PartyFrames"] = {
                [1] = {
                    DisabledComponentsMigrated = true,
                    Spacing = 3,
                    Position = {
                        y = -466,
                        x = 446,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    IncludePlayer = true,
                    DisabledComponents = {
                        "DefensiveIcon",
                        "CrowdControlIcon",
                        "Status",
                    },
                    ComponentPositions = {
                        RoleIcon = {
                            posY = 15.0,
                            offsetX = 4.9,
                            posX = 74.9,
                            justifyH = "RIGHT",
                            offsetY = 4.9,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        Debuffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 18,
                            },
                            posX = 110,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        LeaderIcon = {
                            posY = 20.0,
                            offsetX = 10,
                            posX = -69.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        MarkerIcon = {
                            posY = 18.0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        CrowdControlIcon = {
                            offsetX = 0,
                            offsetY = 2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        DefensiveIcon = {
                            offsetX = 2,
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        HealthText = {
                            posY = 0,
                            offsetX = 5,
                            posX = 74.9,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        PrivateAuraAnchor = {
                            posY = 0,
                            offsetX = 0,
                            overrides = {
                                Scale = 1.2,
                            },
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Name = {
                            posY = 0,
                            offsetX = 4.9,
                            posX = -74.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        ResIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        PhaseIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 18,
                            },
                            posX = -110,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        SummonIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                },
            },
            ["Orbit_ActionBars"] = {
                [1] = {
                    NumActionBars = 5,
                    Scale = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 12.2,
                        relativeTo = "UIParent",
                        point = "BOTTOM",
                        relativePoint = "BOTTOM",
                        x = 0.3,
                    },
                    Anchor = false,
                    NumIcons = 12,
                    Rows = 1,
                    GlobalComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            posY = -15,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            posY = 12,
                            offsetX = 1,
                            posX = 13,
                            justifyH = "RIGHT",
                            offsetY = 7,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        MacroText = {
                            overrides = {
                                FontSize = 10,
                            },
                            posY = -14,
                            offsetX = 1,
                            posX = -7,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                },
                [2] = {
                    Scale = 90,
                    Position = {
                        y = 3,
                        relativeTo = "OrbitActionBar1",
                        point = "BOTTOMLEFT",
                        relativePoint = "TOPLEFT",
                        x = 13,
                    },
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Rows = 1,
                    IconPadding = 2,
                    NumIcons = 12,
                },
                [3] = {
                    Scale = 90,
                    Opacity = 100,
                    Position = {
                        y = 11.5,
                        x = -319.1,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    Rows = 2,
                    IconPadding = 1,
                    NumIcons = 8,
                },
                [4] = {
                    Scale = 90,
                    Opacity = 100,
                    Position = {
                        y = 11.5,
                        x = 319.1,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    Rows = 2,
                    IconPadding = 1,
                    NumIcons = 8,
                },
                [5] = {
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = -5,
                        x = 5,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    NumIcons = 12,
                    HideEmptyButtons = true,
                    Rows = 1,
                },
                [6] = {
                    Rows = 12,
                    IconPadding = 2,
                    Position = {
                        y = -40,
                        x = -3,
                        point = "RIGHT",
                    },
                },
                [7] = {
                    Rows = 12,
                    IconPadding = 2,
                },
                [8] = {
                    Scale = 90,
                    Rows = 12,
                    IconPadding = 2,
                    NumIcons = 12,
                },
                [9] = {
                    Scale = 80,
                    OutOfCombatFade = false,
                    HideEmptyButtons = true,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    Opacity = 0,
                    IconPadding = 2,
                    Rows = 1,
                },
                [10] = {
                    Scale = 80,
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Opacity = 100,
                    IconPadding = 2,
                    Rows = 1,
                },
                [11] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Rows = 1,
                    IconPadding = 2,
                    Scale = 80,
                },
                [12] = {
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 271,
                        x = -252,
                        point = "BOTTOM",
                    },
                },
                [13] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
            },
            ["Orbit_PlayerFrame"] = {
                [1] = {
                    ShowCombatIcon = true,
                    PortraitStyle = "3d",
                    ShowAbsorbs = true,
                    Is3D = true,
                    PortraitShape = "square",
                    Anchor = false,
                    TextSize = 12,
                    EnablePlayerPower = true,
                    PortraitMirror = false,
                    ShowHealAbsorbs = true,
                    DisabledComponents = {
                        "Status",
                        "Portrait",
                    },
                    Width = 160,
                    PortraitBorder = true,
                    Position = {
                        y = 297.0,
                        x = -363.8,
                        point = "BOTTOM",
                    },
                    Height = 40,
                    PortraitScale = 155,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            posY = 14.0,
                            posX = 82.9,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        GroupPositionText = {
                            offsetX = -3,
                            posY = -14.0,
                            posX = 82.9,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            posY = 20.0,
                            posX = -69.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 4.9,
                            posY = 0,
                            posX = 74.9,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RestingIcon = {
                            overrides = {
                                Scale = 0.5,
                            },
                            posY = 15.0,
                            offsetX = 10,
                            posX = -69.9,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 20.0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        RoleIcon = {
                            offsetX = 10,
                            posY = 17.0,
                            posX = 69.9,
                            justifyH = "RIGHT",
                            offsetY = 3,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        CombatIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Portrait = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 4,
                            anchorY = "CENTER",
                        },
                    },
                    ShowLevel = true,
                },
            },
            ["Orbit_TargetBuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    Anchor = {
                        target = "OrbitTargetPower",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    IconsPerRow = 8,
                    Scale = 100,
                },
            },
            ["Orbit_BossFrames"] = {
                [1] = {
                    CastBarHeight = 18,
                    Scale = 100,
                    DebuffSize = 32,
                    DisabledComponents = {
                        "Buffs",
                    },
                    MaxDebuffs = 4,
                    Width = 120,
                    DebuffPosition = "Left",
                    Position = {
                        y = 62.73932989297293,
                        x = -493.401727499577,
                        point = "RIGHT",
                    },
                    Anchor = false,
                    CastBarIcon = false,
                    Height = 25,
                    Spacing = 22,
                    ComponentPositions = {
                        CastBar = {
                            posY = -25.16239408534428,
                            subComponents = {
                                Timer = {
                                    offsetX = 4,
                                    justifyH = "RIGHT",
                                    offsetY = 0,
                                    anchorX = "RIGHT",
                                    anchorY = "CENTER",
                                },
                                Text = {
                                    offsetX = 4,
                                    justifyH = "LEFT",
                                    offsetY = 0,
                                    anchorX = "LEFT",
                                    anchorY = "CENTER",
                                },
                            },
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = -9.846154207308631,
                            anchorX = "CENTER",
                            anchorY = "BOTTOM",
                        },
                        Debuffs = {
                            posY = 0,
                            offsetX = -2,
                            overrides = {
                                MaxIcons = 4,
                                MaxRows = 1,
                                IconSize = 25,
                            },
                            posX = -95,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            posY = 0,
                            offsetX = 5,
                            posX = -54.89745330810547,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        HealthText = {
                            posY = 0,
                            offsetX = 5,
                            posX = 54.89745330810547,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Buffs = {
                            overrides = {
                                MaxIcons = 3,
                                MaxRows = 1,
                                IconSize = 20,
                            },
                            offsetX = -2,
                            posX = 95,
                            posY = 0,
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            posY = 12.58118438720703,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                    },
                    CastBarPosition = "Below",
                },
            },
            ["Orbit_PlayerPower"] = {
                [1] = {
                    ShowText = false,
                    Anchor = {
                        target = "OrbitPlayerResources",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    Height = 10,
                    DisabledComponents = {
                    },
                    ComponentPositions = {
                        Text = {
                            offsetX = 4.923077103654316,
                            posY = 0,
                            posX = 179.9658185669189,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                    },
                },
            },
            ["Orbit_PlayerResources"] = {
                [1] = {
                    DividerSize = 2,
                    ShowText = true,
                    Spacing = 2,
                    Height = 12,
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    TextSize = 15,
                    Width = 200,
                },
            },
            ["Orbit_TargetFrame"] = {
                [2] = {
                    PortraitMirror = true,
                    AuraSize = 20,
                    Is3D = false,
                    PortraitStyle = "2d",
                    DisabledComponents = {
                        "Portrait",
                    },
                    PortraitShape = "square",
                    EnableTargetPower = true,
                    PortraitBorder = true,
                    MaxBuffs = 16,
                    Position = {
                        y = -273.5,
                        x = 363.8,
                        point = "CENTER",
                    },
                    Anchor = false,
                    PortraitScale = 125,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = 0,
                            posY = 15.0,
                            posX = 79.9,
                            justifyH = "LEFT",
                            offsetY = 4.9,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -74.9,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            posY = 20.0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            posY = 0,
                            posX = 74.9,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -6.3,
                            posY = -12.0,
                            posX = 86.2,
                            justifyH = "LEFT",
                            offsetY = 8.0,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Portrait = {
                            anchorX = "LEFT",
                            offsetY = 0,
                            offsetX = 4,
                            anchorY = "CENTER",
                        },
                    },
                    EnableTargetTarget = true,
                },
            },
            ["Orbit_CombatTimer"] = {
                ["Orbit_CombatTimer"] = {
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 15,
                        edge = "LEFT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                    Scale = 100,
                    Position = {
                        y = 0,
                        relativeTo = "OrbitActionBar3",
                        point = "RIGHT",
                        relativePoint = "LEFT",
                        x = -9,
                    },
                },
            },
            ["Orbit_TargetOfFocusFrame"] = {
                [101] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitFocusBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 100,
                },
            },
            ["Orbit_TargetCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 2,
                        edge = "TOP",
                    },
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            [13] = {
                [13] = {
                    EyeSize = 100,
                    Size = 100,
                },
            },
            ["Orbit_PlayerCastBar"] = {
                [1] = {
                    CastBarTextSize = 10,
                    CastBarHeight = 35,
                    SparkColorCurve = {
                        pins = {
                            {
                                color = { a = 0.263955146074295, b = 1, g = 1, r = 1 },
                                position = 0.5,
                            },
                        },
                    },
                    Position = {
                        y = 217,
                        x = -1,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    CastBarTimer = true,
                    CastBarText = true,
                    CastBarWidth = 300,
                },
            },
            ["Orbit_TargetOfTargetFrame"] = {
                [100] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitTargetBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 100,
                },
            },
            ["Orbit_FocusBuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitFocusPower",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                },
            },
            [14] = {
                [14] = {
                    Size = 70,
                },
            },
            ["Orbit_Portal"] = {
                [1] = {
                    Anchor = false,
                    Position = {
                        y = -118,
                        x = 11,
                        point = "TOPLEFT",
                    },
                },
            },
            ["Orbit_PlayerPetFrame"] = {
                [8] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 90,
                },
            },
            ["Orbit_FocusPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_Performance"] = {
                ["Orbit_Performance"] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 15,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                },
            },
        },
    },
    GlobalSettings = {
        OverlayTexture = "Orbit Gradient",
        BarColorCurve = {
            pins = {
                {
                    color = { a = 1, b = 1, g = 1, r = 1 },
                    type = "class",
                    position = 0,
                },
            },
        },
        BackdropColour = { a = 0.7, b = 0.145, g = 0.145, r = 0.145 },
        TextScale = "Medium",
        BorderSize = 2,
        OverlayAllFrames = false,
        HideWhenMounted = true,
        ClassColorBackground = false,
        FontOutline = "OUTLINE",
        UseClassColors = true,
        BarColor = { a = 1, b = 0.2, g = 0.8, r = 0.2 },
        Font = "PT Sans Narrow",
        Texture = "Solid",
    },
}
