local _, Orbit = ...

-- [ DEFAULT PROFILE ]-------------------------------------------------------------------------------
-- Preconfigured layout for new profiles (first-time users get this)
Orbit.Profile = Orbit.Profile or {}
Orbit.Profile.defaults = {
    Layouts = {
        ["Orbit"] = {
            ["Orbit_FocusCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    CastBarWidth = 200,
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_FocusFrame"] = {
                [3] = {
                    EnableFocusTarget = true,
                    ReactionColour = false,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -8,
                            justifyH = "LEFT",
                            offsetY = 9,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 30,
                        edge = "RIGHT",
                        align = "BOTTOM",
                    },
                    Height = 40,
                    EnableFocusPower = true,
                    Width = 160,
                },
            },
            ["Orbit_QueueStatus"] = {
                ["Orbit_QueueStatus"] = {
                    Anchor = false,
                    Position = {
                        y = -3.5,
                        x = -342.3,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_BagBar"] = {
                ["Orbit_BagBar"] = {
                    Anchor = {
                        target = "OrbitMicroMenuContainer",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Opacity = 100,
                    Scale = 100,
                },
            },
            ["Orbit_TargetDebuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    Anchor = {
                        target = "OrbitTargetCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    IconsPerRow = 8,
                },
            },
            ["Orbit_Status"] = {
                [1] = {
                    Height = 16,
                    Position = "TOP",
                },
            },
            ["Orbit_FocusDebuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    IconsPerRow = 8,
                    Scale = 100,
                    Anchor = {
                        target = "OrbitFocusCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
            },
            ["Orbit_TalkingHead"] = {
                ["Orbit_TalkingHead"] = {
                    Anchor = false,
                    Scale = 60,
                    Position = {
                        y = -122.5,
                        x = 0,
                        point = "TOP",
                    },
                },
            },
            ["Orbit_CooldownViewer"] = {
                [1] = {
                    IconLimit = 10,
                    Opacity = 100,
                    IconPadding = 1,
                    aspectRatio = "4:3",
                    Position = {
                        y = -223.8,
                        x = 0,
                        point = "CENTER",
                    },
                    Anchor = false,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    IconSize = 120,
                },
                [2] = {
                    IconLimit = 10,
                    Opacity = 100,
                    IconPadding = 1,
                    aspectRatio = "4:3",
                    Position = {
                        y = -13,
                        relativeTo = "OrbitEssentialCooldowns",
                        point = "TOP",
                        relativePoint = "BOTTOM",
                        x = 0,
                    },
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10.5,
                            offsetX = 0.6,
                            posX = -16.2,
                            justifyH = "LEFT",
                            offsetY = 5.4,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    IconSize = 90,
                },
                [3] = {
                    IconLimit = 10,
                    Opacity = 100,
                    IconPadding = 1,
                    aspectRatio = "4:3",
                    Position = {
                        y = 0.9,
                        relativeTo = "OrbitPlayerResources",
                        point = "BOTTOM",
                        relativePoint = "TOP",
                        x = 0,
                    },
                    Anchor = {
                        target = "OrbitPlayerResources",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            offsetX = 2,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    IconSize = 100,
                },
            },
            ["Orbit_TargetPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_MicroMenu"] = {
                ["Orbit_MicroMenu"] = {
                    Anchor = false,
                    Padding = -5,
                    Rows = 1,
                    Position = {
                        y = 0.55,
                        x = 0,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_PartyFrames"] = {
                [1] = {
                    DisabledComponentsMigrated = true,
                    Anchor = false,
                    Position = {
                        y = -465.2,
                        x = 445.3,
                        point = "TOPLEFT",
                    },
                    IncludePlayer = true,
                    ComponentPositions = {
                        RoleIcon = {
                            offsetX = 10,
                            justifyH = "RIGHT",
                            offsetY = 3,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = -2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        PhaseIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ResIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        SummonIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Spacing = 3,
                },
            },
            ["Orbit_ActionBars"] = {
                [1] = {
                    NumActionBars = 8,
                    Scale = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 6.3,
                        relativeTo = "UIParent",
                        point = "BOTTOM",
                        relativePoint = "BOTTOM",
                        x = 0,
                    },
                    Anchor = false,
                    NumIcons = 12,
                    GlobalComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            posY = -15,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        MacroText = {
                            overrides = {
                                FontSize = 10,
                            },
                            posY = -13.7,
                            offsetX = 0.7,
                            posX = -6.2,
                            justifyH = "LEFT",
                            offsetY = 5.3,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            posY = 11.4,
                            offsetX = 0.6,
                            posX = 12.2,
                            justifyH = "RIGHT",
                            offsetY = 6.6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    Rows = 1,
                },
                [2] = {
                    NumIcons = 12,
                    Position = {
                        y = 2.8,
                        relativeTo = "OrbitActionBar1",
                        point = "BOTTOMLEFT",
                        relativePoint = "TOPLEFT",
                        x = 12.6,
                    },
                    Scale = 90,
                    Rows = 1,
                    IconPadding = 2,
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
                [3] = {
                    Rows = 2,
                    NumIcons = 8,
                    Position = {
                        y = 2.1,
                        relativeTo = "OrbitActionBar2",
                        point = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        x = -9.8,
                    },
                    Scale = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 15,
                        edge = "LEFT",
                        align = "TOP",
                    },
                },
                [4] = {
                    NumIcons = 8,
                    Rows = 2,
                    Position = {
                        y = -2.1,
                        relativeTo = "OrbitActionBar1",
                        point = "BOTTOMLEFT",
                        relativePoint = "BOTTOMRIGHT",
                        x = 9.8,
                    },
                    Scale = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 15,
                        edge = "RIGHT",
                        align = "BOTTOM",
                    },
                },
                [5] = {
                    Opacity = 100,
                    HideEmptyButtons = true,
                    Position = {
                        y = -4.3,
                        x = 5,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    NumIcons = 12,
                    IconPadding = 2,
                    Rows = 1,
                },
                [6] = {
                    Anchor = false,
                    Rows = 12,
                    IconPadding = 2,
                    Position = {
                        y = -39.9,
                        x = -2.9,
                        point = "RIGHT",
                    },
                },
                [7] = {
                    Anchor = {
                        target = "OrbitActionBar6",
                        padding = 2,
                        edge = "LEFT",
                        align = "BOTTOM",
                    },
                    Rows = 12,
                    IconPadding = 2,
                },
                [8] = {
                    Anchor = {
                        target = "OrbitActionBar7",
                        padding = 2,
                        edge = "LEFT",
                        align = "BOTTOM",
                    },
                    IconPadding = 2,
                    Scale = 100,
                    Rows = 12,
                    NumIcons = 12,
                },
                [9] = {
                    Opacity = 0,
                    IconPadding = 2,
                    Position = {
                        y = 3.2,
                        relativeTo = "OrbitActionBar2",
                        point = "BOTTOM",
                        relativePoint = "TOP",
                        x = 0,
                    },
                    Scale = 80,
                    Rows = 1,
                    HideEmptyButtons = true,
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                },
                [10] = {
                    Rows = 1,
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Opacity = 100,
                    IconPadding = 2,
                    Scale = 80,
                },
                [11] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Rows = 1,
                    IconPadding = 2,
                    Scale = 80,
                },
                [12] = {
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 270.4,
                        x = -252,
                        point = "BOTTOM",
                    },
                },
            },
            ["Orbit_PlayerFrame"] = {
                [1] = {
                    ShowCombatIcon = true,
                    EnablePlayerPower = true,
                    ShowHealAbsorbs = true,
                    Width = 160,
                    Anchor = false,
                    ComponentPositions = {
                        RoleIcon = {
                            offsetX = 10,
                            posY = 17,
                            posX = 70,
                            justifyH = "RIGHT",
                            offsetY = 3,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        GroupPositionText = {
                            posY = -35,
                            offsetX = 5,
                            posX = 75,
                            justifyH = "RIGHT",
                            offsetY = -15,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            posY = 20,
                            posX = -70,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            posY = 0,
                            posX = 75,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RestingIcon = {
                            offsetX = -30,
                            posY = 0,
                            posX = -110,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            posY = 0,
                            posX = -75,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        LevelText = {
                            offsetX = -3,
                            posY = 15,
                            posX = 83,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        CombatIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            posY = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            anchorX = "RIGHT",
                            offsetY = -2,
                            offsetX = -2,
                            anchorY = "TOP",
                        },
                    },
                    Position = {
                        y = 301.5,
                        x = -346.8,
                        point = "BOTTOM",
                    },
                    Height = 40,
                    ShowAbsorbs = true,
                    TextSize = 12,
                    ShowLevel = true,
                },
            },
            ["Orbit_TargetBuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    Scale = 100,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitTargetPower",
                        padding = -2,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                },
            },
            ["Orbit_BossFrames"] = {
                [1] = {
                    CastBarHeight = 18,
                    Scale = 100,
                    MaxDebuffs = 4,
                    Width = 120,
                    DebuffPosition = "Left",
                    Position = {
                        y = 52.5,
                        x = -434.3,
                        point = "RIGHT",
                    },
                    CastBarIcon = false,
                    Height = 25,
                    Anchor = false,
                    DebuffSize = 32,
                    CastBarPosition = "Below",
                },
            },
            ["Orbit_PlayerPower"] = {
                [1] = {
                    Height = 10,
                    ShowText = false,
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                },
            },
            ["Orbit_PlayerCastBar"] = {
                [1] = {
                    CastBarHeight = 35,
                    CastBarWidth = 300,
                    CastBarTextSize = 10,
                    Anchor = false,
                    CastBarTimer = true,
                    CastBarText = true,
                    Position = {
                        y = 216.4,
                        x = -0.6,
                        point = "BOTTOM",
                    },
                },
            },
            [13] = {
                [13] = {
                    Size = 100,
                    EyeSize = 100,
                },
            },
            ["Orbit_CombatTimer"] = {
                ["Orbit_CombatTimer"] = {
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 15,
                        edge = "LEFT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                    Scale = 100,
                    Position = {
                        y = 0,
                        relativeTo = "OrbitActionBar3",
                        point = "RIGHT",
                        relativePoint = "LEFT",
                        x = -8.4,
                    },
                },
            },
            ["Orbit_TargetOfFocusFrame"] = {
                [101] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitFocusBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 100,
                },
            },
            ["Orbit_PlayerResources"] = {
                [1] = {
                    ShowText = true,
                    Spacing = 2,
                    Height = 10,
                    Anchor = {
                        target = "OrbitPlayerPower",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    TextSize = 15,
                    Width = 200,
                },
            },
            ["Orbit_TargetFrame"] = {
                [2] = {
                    EnableTargetPower = true,
                    MaxBuffs = 16,
                    AuraSize = 20,
                    Anchor = false,
                    Position = {
                        y = -269.7,
                        x = 346.3,
                        point = "CENTER",
                    },
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -8,
                            justifyH = "LEFT",
                            offsetY = 10,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                    EnableTargetTarget = true,
                },
            },
            ["Orbit_TargetCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 2,
                        edge = "TOP",
                    },
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_TargetOfTargetFrame"] = {
                [100] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitTargetBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 100,
                },
            },
            ["Orbit_FocusBuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    Anchor = {
                        target = "OrbitFocusPower",
                        padding = -2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    IconsPerRow = 8,
                },
            },
            [14] = {
                [14] = {
                    Size = 70,
                },
            },
            ["Orbit_Portal"] = {
                [1] = {
                    Anchor = false,
                    Position = {
                        y = -117.6,
                        x = 10.6,
                        point = "TOPLEFT",
                    },
                },
            },
            ["Orbit_PlayerPetFrame"] = {
                [8] = {
                    Height = 20,
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    DisabledComponents = {
                        "HealthText",
                    },
                    Width = 90,
                },
            },
            ["Orbit_FocusPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_Performance"] = {
                ["Orbit_Performance"] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 15,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                },
            },
        },
    },
}
