local _, Orbit = ...

-- [ DEFAULT PROFILE ]-------------------------------------------------------------------------------
-- Preconfigured layout for new profiles (first-time users get this)
Orbit.Profile = Orbit.Profile or {}
Orbit.Profile.defaults = {
    Layouts = {
        ["Orbit"] = {
            ["Orbit_FocusCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    CastBarWidth = 200,
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_FocusFrame"] = {
                [3] = {
                    EnableFocusTarget = true,
                    ReactionColour = false,
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -8,
                            justifyH = "LEFT",
                            offsetY = 9,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 30,
                        edge = "RIGHT",
                        align = "BOTTOM",
                    },
                    Height = 40,
                    EnableFocusPower = true,
                    Width = 160,
                },
            },
            ["Orbit_QueueStatus"] = {
                ["Orbit_QueueStatus"] = {
                    Anchor = false,
                    Position = {
                        y = -4,
                        x = -343,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_BagBar"] = {
                ["Orbit_BagBar"] = {
                    Anchor = {
                        target = "OrbitMicroMenuContainer",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Opacity = 100,
                    Scale = 100,
                },
            },
            ["Orbit_TargetDebuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitTargetCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                },
            },
            ["Orbit_Status"] = {
                [1] = {
                    Height = 16,
                    Position = "TOP",
                },
            },
            ["Orbit_FocusDebuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    Scale = 100,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitFocusCastBar",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                },
            },
            ["Orbit_TalkingHead"] = {
                ["Orbit_TalkingHead"] = {
                    Anchor = false,
                    Scale = 60,
                    Position = {
                        y = -123,
                        x = 0,
                        point = "TOP",
                    },
                },
            },
            ["Orbit_MicroMenu"] = {
                ["Orbit_MicroMenu"] = {
                    Anchor = false,
                    Padding = -5,
                    Rows = 1,
                    Position = {
                        y = 1,
                        x = 0,
                        point = "BOTTOMRIGHT",
                    },
                },
            },
            ["Orbit_CooldownViewer"] = {
                [1] = {
                    Anchor = false,
                    aspectRatio = "4:3",
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    Position = {
                        y = -225,
                        x = 0,
                        point = "CENTER",
                    },
                    IconSize = 120,
                    Opacity = 100,
                    IconPadding = 2,
                    IconLimit = 12,
                },
                [2] = {
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    aspectRatio = "4:3",
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -11,
                            offsetX = 1,
                            posX = -17,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                    Position = {
                        y = -13,
                        relativeTo = "OrbitEssentialCooldowns",
                        point = "TOP",
                        relativePoint = "BOTTOM",
                        x = 0,
                    },
                    IconSize = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    IconLimit = 8,
                },
                [3] = {
                    IconLimit = 10,
                    Opacity = 100,
                    IconPadding = 1,
                    aspectRatio = "4:3",
                    Position = {
                        y = -200,
                        x = 0,
                        point = "CENTER",
                    },
                    IconSize = 100,
                    PandemicGlowType = 1,
                    ComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Charges = {
                            posY = -10,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Stacks = {
                            posY = -10,
                            offsetX = 1,
                            posX = -15,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            offsetX = 2,
                            justifyH = "RIGHT",
                            offsetY = 2,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    Anchor = false,
                },
                [20] = {
                },
            },
            ["Orbit_TargetPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_PartyFrames"] = {
                [1] = {
                    DisabledComponentsMigrated = true,
                    Anchor = false,
                    Position = {
                        y = -466,
                        x = 446,
                        point = "TOPLEFT",
                    },
                    Spacing = 3,
                    ComponentPositions = {
                        RoleIcon = {
                            offsetX = 10,
                            justifyH = "RIGHT",
                            offsetY = 3,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        LeaderIcon = {
                            offsetX = 10,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        SummonIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        PhaseIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ResIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = -2,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                    },
                    IncludePlayer = true,
                },
            },
            ["Orbit_ActionBars"] = {
                [1] = {
                    NumActionBars = 8,
                    Scale = 90,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 7,
                        relativeTo = "UIParent",
                        point = "BOTTOM",
                        relativePoint = "BOTTOM",
                        x = 0,
                    },
                    Anchor = false,
                    NumIcons = 12,
                    Rows = 1,
                    GlobalComponentPositions = {
                        Timer = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        Stacks = {
                            posY = -15,
                            offsetX = 1,
                            posX = 15,
                            justifyH = "RIGHT",
                            offsetY = 5,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        Keybind = {
                            posY = 12,
                            offsetX = 1,
                            posX = 13,
                            justifyH = "RIGHT",
                            offsetY = 7,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        MacroText = {
                            offsetX = 1,
                            overrides = {
                                FontSize = 10,
                            },
                            posY = -14,
                            posX = -7,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "LEFT",
                            anchorY = "BOTTOM",
                        },
                    },
                },
                [2] = {
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Position = {
                        y = 3,
                        relativeTo = "OrbitActionBar1",
                        point = "BOTTOMLEFT",
                        relativePoint = "TOPLEFT",
                        x = 13,
                    },
                    Scale = 90,
                    NumIcons = 12,
                    IconPadding = 2,
                    Rows = 1,
                },
                [3] = {
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 15,
                        edge = "LEFT",
                        align = "TOP",
                    },
                    Opacity = 100,
                    Position = {
                        y = 3,
                        relativeTo = "OrbitActionBar2",
                        point = "TOPRIGHT",
                        relativePoint = "TOPLEFT",
                        x = -10,
                    },
                    Scale = 90,
                    Rows = 2,
                    IconPadding = 2,
                    NumIcons = 8,
                },
                [4] = {
                    Anchor = {
                        target = "OrbitActionBar1",
                        padding = 15,
                        edge = "RIGHT",
                        align = "BOTTOM",
                    },
                    Opacity = 100,
                    Position = {
                        y = -3,
                        relativeTo = "OrbitActionBar1",
                        point = "BOTTOMLEFT",
                        relativePoint = "BOTTOMRIGHT",
                        x = 10,
                    },
                    Scale = 90,
                    NumIcons = 8,
                    IconPadding = 2,
                    Rows = 2,
                },
                [5] = {
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = -5,
                        x = 5,
                        point = "TOPLEFT",
                    },
                    Anchor = false,
                    NumIcons = 12,
                    HideEmptyButtons = true,
                    Rows = 1,
                },
                [6] = {
                    Anchor = false,
                    Rows = 12,
                    IconPadding = 2,
                    Position = {
                        y = -40,
                        x = -3,
                        point = "RIGHT",
                    },
                },
                [7] = {
                    Anchor = {
                        target = "OrbitActionBar6",
                        padding = 2,
                        edge = "LEFT",
                        align = "BOTTOM",
                    },
                    Rows = 12,
                    IconPadding = 2,
                },
                [8] = {
                    NumIcons = 12,
                    Scale = 100,
                    Rows = 12,
                    IconPadding = 2,
                    Anchor = {
                        target = "OrbitActionBar7",
                        padding = 2,
                        edge = "LEFT",
                        align = "BOTTOM",
                    },
                },
                [9] = {
                    Anchor = {
                        target = "OrbitActionBar2",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    HideEmptyButtons = true,
                    Position = {
                        y = 4,
                        relativeTo = "OrbitActionBar2",
                        point = "BOTTOM",
                        relativePoint = "TOP",
                        x = 0,
                    },
                    Scale = 80,
                    Rows = 1,
                    IconPadding = 2,
                    Opacity = 0,
                },
                [10] = {
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    Scale = 80,
                    Rows = 1,
                    IconPadding = 2,
                    Opacity = 100,
                },
                [11] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 2,
                        edge = "TOP",
                        align = "RIGHT",
                    },
                    Rows = 1,
                    IconPadding = 2,
                    Scale = 80,
                },
                [12] = {
                    Anchor = false,
                    Opacity = 100,
                    IconPadding = 2,
                    Position = {
                        y = 271,
                        x = -252,
                        point = "BOTTOM",
                    },
                },
                [13] = {
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 2,
                        edge = "LEFT",
                        align = "BOTTOM",
                    },
                },
            },
            ["Orbit_PlayerFrame"] = {
                [1] = {
                    ShowCombatIcon = true,
                    EnablePlayerPower = true,
                    ShowHealAbsorbs = true,
                    DisabledComponents = {
                    },
                    Width = 160,
                    Height = 40,
                    TextSize = 12,
                    Position = {
                        y = 302,
                        x = -362,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    ShowAbsorbs = true,
                    ComponentPositions = {
                        RoleIcon = {
                            posY = 17,
                            offsetX = 10,
                            posX = 70,
                            justifyH = "RIGHT",
                            offsetY = 3,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        GroupPositionText = {
                            posY = -15,
                            offsetX = 0,
                            posX = 85,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                        LeaderIcon = {
                            posY = 20,
                            offsetX = 10,
                            posX = -70,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            posY = 0,
                            offsetX = 5,
                            posX = 75,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        RestingIcon = {
                            overrides = {
                                Scale = 0.5,
                            },
                            posY = 15,
                            offsetX = 10,
                            posX = -70,
                            justifyH = "LEFT",
                            offsetY = 5,
                            anchorX = "LEFT",
                            anchorY = "TOP",
                        },
                        Name = {
                            posY = 0,
                            offsetX = 5,
                            posX = -75,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        MarkerIcon = {
                            posY = 20,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "TOP",
                        },
                        CombatIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        ReadyCheckIcon = {
                            posY = 0,
                            offsetX = 0,
                            posX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                        LevelText = {
                            posY = 15,
                            offsetX = 1,
                            posX = 84,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                    },
                    ShowLevel = true,
                },
            },
            ["Orbit_TargetBuffs"] = {
                [1] = {
                    MaxRows = 2,
                    Spacing = 2,
                    IconsPerRow = 8,
                    Scale = 100,
                    Anchor = {
                        target = "OrbitTargetPower",
                        padding = -2,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                },
            },
            ["Orbit_BossFrames"] = {
                [1] = {
                    CastBarHeight = 18,
                    CastBarPosition = "Below",
                    MaxDebuffs = 4,
                    Width = 120,
                    DebuffPosition = "Left",
                    Scale = 100,
                    Position = {
                        y = 53,
                        x = -435,
                        point = "RIGHT",
                    },
                    Height = 25,
                    DebuffSize = 32,
                    Anchor = false,
                    CastBarIcon = false,
                },
            },
            ["Orbit_PlayerPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitEssentialCooldowns",
                        padding = 2,
                        edge = "TOP",
                        align = "LEFT",
                    },
                    ShowText = false,
                },
            },
            ["Orbit_PlayerCastBar"] = {
                [1] = {
                    CastBarWidth = 300,
                    CastBarTextSize = 10,
                    Position = {
                        y = 217,
                        x = -1,
                        point = "BOTTOM",
                    },
                    Anchor = false,
                    CastBarTimer = true,
                    CastBarText = true,
                    CastBarHeight = 35,
                },
            },
            ["Orbit_PlayerResources"] = {
                [1] = {
                    ShowText = true,
                    Spacing = 2,
                    Height = 12,
                    Anchor = {
                        target = "OrbitPlayerPower",
                        padding = 2,
                        edge = "TOP",
                        align = "CENTER",
                    },
                    TextSize = 15,
                    Width = 200,
                },
            },
            ["Orbit_TargetFrame"] = {
                [2] = {
                    EnableTargetPower = true,
                    MaxBuffs = 16,
                    AuraSize = 20,
                    Anchor = false,
                    Position = {
                        y = -270,
                        x = 363,
                        point = "CENTER",
                    },
                    ComponentPositions = {
                        LevelText = {
                            offsetX = -3,
                            justifyH = "LEFT",
                            offsetY = 6,
                            anchorX = "RIGHT",
                            anchorY = "TOP",
                        },
                        HealthText = {
                            offsetX = 5,
                            justifyH = "RIGHT",
                            offsetY = 0,
                            anchorX = "RIGHT",
                            anchorY = "CENTER",
                        },
                        Name = {
                            offsetX = 5,
                            justifyH = "LEFT",
                            offsetY = 0,
                            anchorX = "LEFT",
                            anchorY = "CENTER",
                        },
                        RareEliteIcon = {
                            offsetX = -8,
                            justifyH = "LEFT",
                            offsetY = 10,
                            anchorX = "RIGHT",
                            anchorY = "BOTTOM",
                        },
                    },
                    EnableTargetTarget = true,
                },
            },
            ["Orbit_TargetCastBar"] = {
                [1] = {
                    Anchor = {
                        target = "OrbitTargetFrame",
                        padding = 2,
                        edge = "TOP",
                    },
                    CastBarHeight = 18,
                    CastBarTextSize = 10,
                },
            },
            ["Orbit_CombatTimer"] = {
                ["Orbit_CombatTimer"] = {
                    Anchor = {
                        target = "OrbitActionBar3",
                        padding = 15,
                        edge = "LEFT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                    Scale = 100,
                    Position = {
                        y = 0,
                        relativeTo = "OrbitActionBar3",
                        point = "RIGHT",
                        relativePoint = "LEFT",
                        x = -9,
                    },
                },
            },
            [13] = {
                [13] = {
                    EyeSize = 100,
                    Size = 100,
                },
            },
            ["Orbit_TargetOfFocusFrame"] = {
                [101] = {
                    DisabledComponents = {
                        "HealthText",
                    },
                    Height = 20,
                    Anchor = {
                        target = "OrbitFocusBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 100,
                },
            },
            ["Orbit_TargetOfTargetFrame"] = {
                [100] = {
                    DisabledComponents = {
                        "HealthText",
                    },
                    Height = 20,
                    Anchor = {
                        target = "OrbitTargetBuffsFrame",
                        padding = 10,
                        edge = "BOTTOM",
                        align = "RIGHT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 100,
                },
            },
            ["Orbit_FocusBuffs"] = {
                [1] = {
                    Scale = 100,
                    MaxRows = 2,
                    IconsPerRow = 8,
                    Anchor = {
                        target = "OrbitFocusPower",
                        padding = -2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                },
            },
            [14] = {
                [14] = {
                    Size = 70,
                },
            },
            ["Orbit_Portal"] = {
                [1] = {
                    Anchor = false,
                    Position = {
                        y = -118,
                        x = 11,
                        point = "TOPLEFT",
                    },
                },
            },
            ["Orbit_PlayerPetFrame"] = {
                [8] = {
                    DisabledComponents = {
                        "HealthText",
                    },
                    Height = 20,
                    Anchor = {
                        target = "OrbitPlayerFrame",
                        padding = 2,
                        edge = "BOTTOM",
                        align = "LEFT",
                    },
                    ComponentPositions = {
                        Name = {
                            offsetX = 0,
                            justifyH = "CENTER",
                            offsetY = 0,
                            anchorX = "CENTER",
                            anchorY = "CENTER",
                        },
                    },
                    Width = 90,
                },
            },
            ["Orbit_FocusPower"] = {
                [1] = {
                    Height = 10,
                    Anchor = {
                        target = "OrbitFocusFrame",
                        padding = 0,
                        edge = "BOTTOM",
                        align = "CENTER",
                    },
                    ShowText = true,
                    Width = 200,
                },
            },
            ["Orbit_Performance"] = {
                ["Orbit_Performance"] = {
                    Anchor = {
                        target = "OrbitActionBar4",
                        padding = 15,
                        edge = "RIGHT",
                        align = "CENTER",
                    },
                    Opacity = 100,
                },
            },
        },
    },
}
